version: '3.8'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  #######################################
  ############## POSTGRES ###############
  #######################################
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: shine-o_postgres
    volumes:
      #- ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - ${DATA_PATH_HOST}/data:/var/lib/postgresql/data
    ports:
    - "54320:5432"
    networks:
      - intranet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  #######################################
  ############## REDIS ##################
  #######################################    
  redis:
    image: redis:${REDIS_VERSION}
    container_name: shine-o_redis
    ports:
      - "6379:6379"
    networks:
      - intranet

  #######################################
  ############## LOGIN ##################
  #######################################
#  login:
#    image: shine-o/login:${BUILD_VERSION}
#    container_name: shine-o_login
#    depends_on:
#      - postgres
#      - redis
#    build:
#      context: ../../build/package/login
#    volumes:
#      - ./../../configs/login.yml:/go/src/app/login.yml
#    networks:
#      - intranet
#    ports:
#      - "9010:9010"
#    command: ["serve", "--config", "/go/src/app/login.yml"]