version: '3.8'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  ######################################
  ############# METRICS ################
  ######################################
  prometheus:
    image: prom/prometheus:latest
    container_name: metrics_prometheus
    restart: unless-stopped
    user: "0"
    volumes:
      - ./deployments/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://alertmanager:9093'
    networks:
      - intranet
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: metrics_node_exporter
    networks:
      - intranet
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: metrics_cadvisor
    restart: unless-stopped
    networks:
      - intranet
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
  loki:
    image: grafana/loki:1.5.0
    container_name: metrics_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - intranet

  promtail:
    image: grafana/promtail:1.5.0
    container_name: metrics_promtail
    volumes:
      - ./output:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - intranet

  grafana:
    image: grafana/grafana
    container_name: metrics_grafana
    restart: unless-stopped
    user: "0"
    networks:
      - intranet
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      #      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com