version: '3.8'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  #######################################
  ############## POSTGRES ###############
  #######################################
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: shineo_postgres
    volumes:
      - ${DATA_PATH_HOST}/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - intranet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  #######################################
  ############## REDIS ##################
  #######################################    
  redis:
    image: redis:${REDIS_VERSION}
    container_name: shineo_redis
    ports:
      - "6379:6379"
    networks:
      - intranet

  ######################################
  ############# DEV BASE IMAGE #########
  ######################################
  build:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_build
    build:
      context: ./
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
  
  ######################################
  ############# MIGRATE LOGIN ##########
  ######################################
  migrate-login:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_login_db_migrate
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 --  go run -mod=vendor  /app/cmd/login/login.go migrate --config "/app/configs/login.docker.yml" --purge "true"'
    tty: false

  ######################################
  ############# MIGRATE WORLD ##########
  ######################################
  migrate-world:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_world_db_migrate
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/world/world.go migrate --config "/app/configs/world.docker.yml"'
    tty: false

  ######################################
  ############# LOGIN ##################
  ######################################
  login:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_login
    depends_on:
      - redis
      - build
      - postgres
      - migrate-login
      - world-master
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "51000:51000"
      - "51001:51001"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -race -mod=vendor /app/cmd/login/login.go serve --config "/app/configs/login.docker.yml"'

  ######################################
  ############# WORLD MASTER ###########
  ######################################
  world-master:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_world-master
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "53000:53000"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/world-master/world-master.go serve --config "/app/configs/world-master.docker.yml"'

  ######################################
  ############# WORLD ##################
  ######################################
  world:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_world
    depends_on:
      - build
      - world-master
      - postgres
      - redis
      - migrate-world
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "52000:52000"
      - "52001:52001"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/world/world.go serve --config "/app/configs/world.docker.yml"'

  ######################################
  ############# ZONE MASTER ############
  ######################################
  zone-master:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_zone-master
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "54000:54000"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/zone-master/zone-master.go serve --config "/app/configs/zone-master.docker.yml"'

  ######################################
  ############# ZONE ###### ############
  ######################################
  zone:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_zone
    depends_on:
      - zone-master
      - build
      - postgres
      - redis
    volumes:
    - ./:/app
    networks:
      - intranet
    ports:
      - "55000:55000"
      - "55001:55001"
    entrypoint: sh -c '/usr/local/bin/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/zone/zone.go serve --config "/app/configs/zone.docker.yml"'

  ######################################
  ############# METRICS ################
  ######################################
  prometheus:
    image: prom/prometheus:latest
    container_name: metrics_prometheus
    restart: unless-stopped
    volumes:
      - ./deployments/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://alertmanager:9093'
    networks:
      - intranet
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: metrics_node_exporter
    networks:
      - intranet
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    container_name: metrics_cadvisor
    restart: unless-stopped
    networks:
      - intranet
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
  loki:
    image: grafana/loki:1.5.0
    container_name: metrics_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - intranet

  promtail:
    image: grafana/promtail:1.5.0
    container_name: metrics_promtail
    volumes:
      - ./output:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - intranet

  grafana:
    image: grafana/grafana
    container_name: metrics_grafana
    restart: unless-stopped
    networks:
      - intranet
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      #      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com