version: '3.8'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  #######################################
  ############## SONARQUBE ##############
  ################################## #####
  sonarqube:
    image: sonarqube:latest
    container_name: shineo_sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"

  #######################################
  ############## POSTGRES ###############
  #######################################
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: shineo_postgres
    volumes:
      - ${DATA_PATH_HOST}/data:/var/lib/postgresql/data
    ports:
    - "54320:5432"
    networks:
      - intranet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  #######################################
  ############## REDIS ##################
  #######################################    
  redis:
    image: redis:${REDIS_VERSION}
    container_name: shineo_redis
    ports:
      - "60000:6379"
    networks:
      - intranet

  ######################################
  ############# DEV BASE IMAGE #########
  ######################################
  build:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_build
    build:
      context: ./
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app

  ######################################
  ############# MIGRATIONS #############
  ######################################
  migrations:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_db_migrate
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/migrations/main.go up'
    tty: false

  ######################################
  ############# LOGIN ##################
  ######################################
  login:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_login
    depends_on:
      - redis
      - build
      - postgres
      - migrations
      - world-master
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "51000:51000"
      - "51001:51001"
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/login/login.go serve --config "/app/configs/login.yml"'

  ######################################
  ############# WORLD MASTER ###########
  ######################################
  world-master:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_world-master
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "53000:53000"
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/world-master/world-master.go serve --config "/app/configs/world-master.yml"'

  ######################################
  ############# WORLD ##################
  ######################################
  world:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_world
    depends_on:
      - build
      - world-master
      - postgres
      - redis
      - migrations
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "52000:52000"
      - "52001:52001"
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/world/world.go serve --config "/app/configs/world.yml"'

  ######################################
  ############# ZONE MASTER ############
  ######################################
  zone-master:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_zone-master
    depends_on:
      - build
      - postgres
      - redis
    networks:
      - intranet
    volumes:
      - ./:/app
    ports:
      - "54000:54000"
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/zone-master/zone-master.go serve --config "/app/configs/zone-master.yml"'

  ######################################
  ############# ZONE ###################
  ######################################
  zone:
    image: shineo/dev-services:${BUILD_VERSION}
    container_name: shineo_zone
    depends_on:
      - zone-master
      - build
      - postgres
      - redis
    volumes:
      - ./:/app
    networks:
      - intranet
    ports:
      - "55000:55000"
      - "55001:55001"
    entrypoint: sh -c '/app/build/wait-for postgres:5432 -- go run -mod=vendor /app/cmd/zone/zone.go serve --config "/app/configs/zone.yml"'