// Code generated by "stringer -type=CustomErrorCode"; DO NOT EDIT.

package persistence

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrDB-0]
	_ = x[ErrItemInvalidAmount-1]
	_ = x[ErrItemInvalidShnId-2]
	_ = x[ErrItemInvalidCharacterId-3]
	_ = x[ErrInventoryFull-4]
	_ = x[ErrCharInvalidSlot-5]
	_ = x[ErrCharNameTaken-6]
	_ = x[ErrCharNoSlot-7]
	_ = x[ErrCharInvalidName-8]
	_ = x[ErrCharInvalidClassGender-9]
}

const _CustomErrorCode_name = "ErrDBErrItemInvalidAmountErrItemInvalidShnIdErrItemInvalidCharacterIdErrInventoryFullErrCharInvalidSlotErrCharNameTakenErrCharNoSlotErrCharInvalidNameErrCharInvalidClassGender"

var _CustomErrorCode_index = [...]uint8{0, 5, 25, 44, 69, 85, 103, 119, 132, 150, 175}

func (i CustomErrorCode) String() string {
	if i < 0 || i >= CustomErrorCode(len(_CustomErrorCode_index)-1) {
		return "CustomErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CustomErrorCode_name[_CustomErrorCode_index[i]:_CustomErrorCode_index[i+1]]
}
