// Code generated by "stringer -type=ErrorCodeZone"; DO NOT EDIT.

package zone

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrDB-0]
}

const _ErrorCodeZone_name = "ErrDB"

var _ErrorCodeZone_index = [...]uint8{0, 5}

func (i ErrorCodeZone) String() string {
	if i < 0 || i >= ErrorCodeZone(len(_ErrorCodeZone_index)-1) {
		return "ErrorCodeZone(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCodeZone_name[_ErrorCodeZone_index[i]:_ErrorCodeZone_index[i+1]]
}
