package shn

type ShineAbState struct {
	DataSize    uint32
	RowsCount   uint32
	FieldSize   uint32
	ColumnCount uint32
	Columns     []ShineColumn `struct:"sizefrom=ColumnCount"`
	ShineRow    []AbState    `struct:"sizefrom=RowsCount"`
}

//struct AbnormalStateInfo
//{
//  unsigned __int16 ID;
//  char InxName[32];
//  ABSTATEINDEX AbStataIndex;
//  unsigned int KeepTimeRatio;
//  char KeepTimePower;
//  char StateGrade;
//  char PartyState1[32];
//  char PartyState2[32];
//  char PartyState3[32];
//  char PartyState4[32];
//  char PartyState5[32];
//  unsigned int PartyRange;
//  unsigned int PartyEnchantNumber;
//  char SubAbState[32];
//  DispelAttr DispelIndex;
//  SubDispelAttr SubDispelIndex;
//  AbStateSaveTypeEnum AbStateSaveType;
//  char MainStateInx[32];
//  char Duplicate;
//};
type AbState struct {
	_                  uint16
	ID                 uint16
	InxName            string `struct:"[32]byte"`
	AbStateIndex       AbStateIndex
	KeepTimeRatio      uint32
	KeepTimePower      byte
	StateGrade         byte
	PartyState1        string `struct:"[32]byte"`
	PartyState2        string `struct:"[32]byte"`
	PartyState3        string `struct:"[32]byte"`
	PartyState4        string `struct:"[32]byte"`
	PartyState5        string `struct:"[32]byte"`
	PartyRange         uint32
	PartyEnchantNumber uint32
	SubAbState         string `struct:"[32]byte"`
	DispelInx          DispelAttr
	SubDispelAttr      SubDispelAttr
	AbStateSaveType    AbStateSaveTypeEnum
	MainStateInx       string `struct:"[32]byte"`
	Duplicate          byte
}

//enum ABSTATEINDEX
//{
//  STA_SEVERBONE = 0x0,
//  STA_REDSLASH = 0x1,
//  STA_BATTLEBLOWSTUN = 0x2,
//  STA_MIGHTYSOULMAIN = 0x3,
//  STA_MIGHTYSOUL = 0x4,
//  STA_MORALEDECREASEWC = 0x5,
//  STA_SPEEDSHIELD = 0x6,
//  STA_HARMDEFECT = 0x7,
//  STA_BERSEKERFRENZY = 0x8,
//  STA_SHOCKBLADESTUN = 0x9,
//  STA_MIGHTYSOUL2 = 0xA,
//  STA_MIGHTYSOUL3 = 0xB,
//  STA_MIGHTYSOUL4 = 0xC,
//  STA_MIGHTYSOUL5 = 0xD,
//  STA_VIOLENCE = 0xE,
//  STA_BUCKLER = 0xF,
//  STA_NEGLECT = 0x10,
//  STA_BREAK = 0x11,
//  STA_BLESSINGMAIN = 0x12,
//  STA_BLESSING = 0x13,
//  STA_SAFEPROTECTION = 0x14,
//  STA_PSYCHICBLUNTSTUN = 0x15,
//  STA_PSYCHICCHOPBLOOD = 0x16,
//  STA_DARKNESSPROTECTION = 0x17,
//  STA_RESTORE = 0x18,
//  STA_HITPROTECTION = 0x19,
//  StaMentalShoutMAIN = 0x1A,
//  StaMentalShout = 0x1B,
//  STA_DIVINESHIELD = 0x1C,
//  StaDivineWeaponWcMAIN = 0x1D,
//  StaDivineWeaponWc = 0x1E,
//  STA_SACRIFICE = 0x1F,
//  STA_CROSSCASTINGCOOLTIME = 0x20,
//  STA_PANICFORCEMR = 0x21,
//  STA_REVERSEORDER = 0x22,
//  STA_HORRORFORCESTR = 0x23,
//  STA_BLESSING2 = 0x24,
//  STA_BLESSING3 = 0x25,
//  STA_BLESSING4 = 0x26,
//  STA_BLESSING5 = 0x27,
//  StaMentalShout2 = 0x28,
//  StaMentalShout3 = 0x29,
//  StaMentalShout4 = 0x2A,
//  StaMentalShout5 = 0x2B,
//  StaDivineWeaponWc2 = 0x2C,
//  StaDivineWeaponWc3 = 0x2D,
//  StaDivineWeaponWc4 = 0x2E,
//  StaDivineWeaponWc5 = 0x2F,
//  STA_REBIRTH = 0x30,
//  STA_DEADLYBLESSING = 0x31,
//  STA_DODGE = 0x32,
//  STA_PURYIMPACTSTUN = 0x33,
//  STA_FORESTWIND = 0x34,
//  StaWindChargeMAIN = 0x35,
//  StaWindCharge = 0x36,
//  STA_BONEARROW = 0x37,
//  STA_SPIRITTHORNENTANGLE = 0x38,
//  STA_POISONSHOT = 0x39,
//  STA_BITEARROW = 0x3A,
//  StaMistChargeMAIN = 0x3B,
//  StaMistCharge = 0x3C,
//  STA_SPIRITFOG = 0x3D,
//  STA_HAWKTALONATKSPEED = 0x3E,
//  STA_NATURECASTINGCOOLTIME = 0x3F,
//  STA_PIERCINGGUARD = 0x40,
//  STA_SHOCKSCREAMWC = 0x41,
//  STA_STINGERUPTIONSLOW = 0x42,
//  StaWindCharge2 = 0x43,
//  StaWindCharge3 = 0x44,
//  StaWindCharge4 = 0x45,
//  StaWindCharge5 = 0x46,
//  StaMistCharge2 = 0x47,
//  StaMistCharge3 = 0x48,
//  StaMistCharge4 = 0x49,
//  StaMistCharge5 = 0x4A,
//  STA_HIDE = 0x4B,
//  STA_BLIND = 0x4C,
//  STA_ENTRAPHIDE = 0x4D,
//  STA_ICEBOLT = 0x4E,
//  STA_LIGHTNINGBOLT = 0x4F,
//  STA_BLUR = 0x50,
//  STA_SOULEDGE = 0x51,
//  STA_RINGSHIELD = 0x52,
//  STA_ICEBLASTSTUN = 0x53,
//  STA_CHAINLIGHTNINGSTUN = 0x54,
//  STA_DRAINMINDFEAR = 0x55,
//  STA_CHAINCASTINGCOOLTIME = 0x56,
//  STA_CURSEMAGICCASTIME = 0x57,
//  STA_FROSTNOVA = 0x58,
//  STA_THUNDERBOLT = 0x59,
//  STA_SOULEDGEMAIN = 0x5A,
//  STA_SOULEDGE2 = 0x5B,
//  STA_SOULEDGE3 = 0x5C,
//  STA_SOULEDGE4 = 0x5D,
//  STA_SOULEDGE5 = 0x5E,
//  STA_DEEPER = 0x5F,
//  STA_MESMERIZE = 0x60,
//  STA_POLYMORPH = 0x61,
//  STA_ICEFIELD = 0x62,
//  STA_MARASTUN = 0x63,
//  STA_KINGSLIMEBLOODING = 0x64,
//  STA_MARLONEENTANGLE = 0x65,
//  STA_NOXENTANGLE = 0x66,
//  STA_SKELKNIGHTBLOODING = 0x67,
//  STA_ROBOACPLUS = 0x68,
//  STA_GOKINGSTUN = 0x69,
//  STA_GOKINGSTRRATE = 0x6A,
//  STA_KINGCALLACPLUS = 0x6B,
//  STA_GHKNIGHTENTANGLE = 0x6C,
//  STA_HUNGRYWOLFBLOODING = 0x6D,
//  STA_KQSKELKNIGHTENTANGLE = 0x6E,
//  STA_MARLONECAPTAINATKSPD = 0x6F,
//  STA_ARCHMAGEBOOKSTUN = 0x70,
//  STA_GHOSTFEAR = 0x71,
//  STA_KQ_BOSSROBOFEAR = 0x72,
//  STA_KQ_BOSSROBO2FEAR = 0x73,
//  STA_NOXSK2BLOODING = 0x74,
//  STA_KQ_G_TBRAIDERCURSE = 0x75,
//  STA_ELFKNIGHTSOULDEXCURSE = 0x76,
//  STA_JOKERTRUMPYTHCURSE = 0x77,
//  STA_KEBINGCURSE = 0x78,
//  STA_KINGCRABCURSE = 0x79,
//  STA_NAVARCURSE = 0x7A,
//  STA_MARACURSE = 0x7B,
//  STA_SKELWARRIORCURSE = 0x7C,
//  STA_ARCHMAGEBOOKCURSE = 0x7D,
//  STA_KARATEMPLERCURSE = 0x7E,
//  STA_SMARTPHINOCURSE = 0x7F,
//  STA_MARLONESOLDIERCURSE = 0x80,
//  STA_OLDFOXCURSE = 0x81,
//  STA_GOBLINMAGECURSE = 0x82,
//  STA_HARKANCURSE = 0x83,
//  STA_DISHARKANCURSE = 0x84,
//  STA_STONIECURSE = 0x85,
//  STA_OGRECURSE = 0x86,
//  STA_MARASAILORCURSE = 0x87,
//  STA_OLDARCHONCURSE = 0x88,
//  STA_KINGMUSHROOMCURSE = 0x89,
//  STA_BCTRUMPYCURSE = 0x8A,
//  STA_KQ_K_BOSSPHINOCURSE = 0x8B,
//  STA_KQ_K_PHINOFLIECURSE = 0x8C,
//  STA_TORTURERBLOODING = 0x8D,
//  STA_SHARPBOARBLOODING = 0x8E,
//  STA_FOBLOODING = 0x8F,
//  STA_BABYWEREBEARBLOODING = 0x90,
//  STA_SENIORTORTURERBLOODING = 0x91,
//  STA_JEWELKEEPERBLOODING = 0x92,
//  STA_SHYLPHBLOODING = 0x93,
//  STA_SGTRUMPYBLOODING = 0x94,
//  STA_KQ_K_SOLIDERBLOODING = 0x95,
//  STA_SKELKNIGHTDISEASE = 0x96,
//  STA_MOB1SLOW = 0x97,
//  STA_MOB2SLOW = 0x98,
//  STA_MOB3SLOW = 0x99,
//  STA_MOB4SLOW = 0x9A,
//  STA_MOB5SLOW = 0x9B,
//  STA_MOB1STUN = 0x9C,
//  STA_MOB2STUN = 0x9D,
//  STA_MOB3STUN = 0x9E,
//  STA_MOB4STUN = 0x9F,
//  STA_MOB5STUN = 0xA0,
//  STA_KQMARASTUN = 0xA1,
//  STA_KQGOBLEKINGSTUN = 0xA2,
//  STA_DIAMASTERSTUN = 0xA3,
//  STA_ANCIENTSTONIESTUN = 0xA4,
//  STA_MOB1ENTANGLE = 0xA5,
//  STA_MOB2ENTANGLE = 0xA6,
//  STA_MOB3ENTANGLE = 0xA7,
//  STA_MOB4ENTANGLE = 0xA8,
//  STA_MOB5ENTANGLE = 0xA9,
//  STA_KQMARLONEENTANGLE = 0xAA,
//  STA_LEGENDARYTREEENTANGLE = 0xAB,
//  STA_GIANTELVENTREEENTANGLE = 0xAC,
//  STA_MOB1POISON = 0xAD,
//  STA_MOB2POISON = 0xAE,
//  STA_MOB3POISON = 0xAF,
//  STA_MOB4POISON = 0xB0,
//  STA_MOB5POISON = 0xB1,
//  STA_MOB6POISON = 0xB2,
//  STA_DIATRUMPYPOISON = 0xB3,
//  STA_MOB1DISEASE1 = 0xB4,
//  STA_MOB2DISEASE1 = 0xB5,
//  STA_MOB3DISEASE1 = 0xB6,
//  STA_MOB4DISEASE1 = 0xB7,
//  STA_MOB5DISEASE1 = 0xB8,
//  STA_MOB6DISEASE1 = 0xB9,
//  STA_MOB1DISEASE2 = 0xBA,
//  STA_MOB2DISEASE2 = 0xBB,
//  STA_MOB3DISEASE2 = 0xBC,
//  STA_MOB4DISEASE2 = 0xBD,
//  STA_MOB5DISEASE2 = 0xBE,
//  STA_MOB6DISEASE2 = 0xBF,
//  STA_MOB1DISEASE3 = 0xC0,
//  STA_MOB2DISEASE3 = 0xC1,
//  STA_MOB3DISEASE3 = 0xC2,
//  STA_MOB4DISEASE3 = 0xC3,
//  STA_MOB5DISEASE3 = 0xC4,
//  STA_MOB6DISEASE3 = 0xC5,
//  STA_MOBIMMORTAL = 0xC6,
//  STA_MOBINVISIBLE = 0xC7,
//  STA_MOBMRPLUS = 0xC8,
//  STA_ACMODE = 0xC9,
//  STA_MRMODE = 0xCA,
//  STA_HELGAACMINUS = 0xCB,
//  STA_BESTLOWCONHPPOTION = 0xCC,
//  STA_LOWCONHPPOTION = 0xCD,
//  STA_NORCONHPPOTION = 0xCE,
//  STA_HIGHCONHPPOTION = 0xCF,
//  STA_BESTHIGHCONHPPOTION = 0xD0,
//  STA_BESTLOWCONSPPOTION = 0xD1,
//  STA_LOWCONSPPOTION = 0xD2,
//  STA_NORCONSPPOTION = 0xD3,
//  STA_HIGHCONSPPOTION = 0xD4,
//  STA_BESTHIGHCONSPPOTION = 0xD5,
//  STA_BESTLOWTHSCROLL = 0xD6,
//  STA_LOWTHSCROLL = 0xD7,
//  STA_NORTHSCROLL = 0xD8,
//  STA_HIGHTHSCROLL = 0xD9,
//  STA_BESTHIGHTHSCROLL = 0xDA,
//  STA_BESTLOWTBSCROLL = 0xDB,
//  STA_LOWTBSCROLL = 0xDC,
//  STA_NORTBSCROLL = 0xDD,
//  STA_HIGHTBSCROLL = 0xDE,
//  STA_BESTHIGHTBSCROLL = 0xDF,
//  STA_BESTLOWMRSCROLL = 0xE0,
//  STA_LOWMRSCROLL = 0xE1,
//  STA_NORMRSCROLL = 0xE2,
//  STA_HIGHMRSCROLL = 0xE3,
//  STA_BESTHIGHMRSCROLL = 0xE4,
//  STA_BESTLOWACSCROLL = 0xE5,
//  STA_LOWACSCROLL = 0xE6,
//  STA_NORACSCROLL = 0xE7,
//  STA_HIGHACSCROLL = 0xE8,
//  STA_BESTHIGHACSCROLL = 0xE9,
//  STA_BESTLOWCRISCROLL = 0xEA,
//  STA_LOWCRISCROLL = 0xEB,
//  STA_NORCRISCROLL = 0xEC,
//  STA_HIGHCRISCROLL = 0xED,
//  STA_BESTHIGHCRISCROLL = 0xEE,
//  STA_BESTLOWMAXHPSCROLL = 0xEF,
//  STA_LOWMAXHPSCROLL = 0xF0,
//  STA_NORMAXHPSCROLL = 0xF1,
//  STA_HIGHMAXHPSCROLL = 0xF2,
//  STA_BESTHIGHMAXHPSCROLL = 0xF3,
//  STA_BESTLOWMAXSPSCROLL = 0xF4,
//  STA_LOWMAXSPSCROLL = 0xF5,
//  STA_NORMAXSPSCROLL = 0xF6,
//  STA_HIGHMAXSPSCROLL = 0xF7,
//  STA_BESTHIGHMAXSPSCROLL = 0xF8,
//  STA_BESTLOWSTRCRISCROLL = 0xF9,
//  STA_LOWSTRCRISCROLL = 0xFA,
//  STA_NORSTRCRISCROLL = 0xFB,
//  STA_HIGHSTRCRISCROLL = 0xFC,
//  STA_BESTHIGHSTRCRISCROLL = 0xFD,
//  STA_BESTLOWDEXSCROLL = 0xFE,
//  STA_LOWDEXSCROLL = 0xFF,
//  STA_NORDEXSCROLL = 0x100,
//  STA_HIGHDEXSCROLL = 0x101,
//  STA_BESTHIGHDEXSCROLL = 0x102,
//  STA_BESTLOWACMRSCROLL = 0x103,
//  STA_LOWACMRSCROLL = 0x104,
//  STA_NORACMRSCROLL = 0x105,
//  STA_HIGHACMRSCROLL = 0x106,
//  STA_BESTHIGHACMRSCROLL = 0x107,
//  STA_NORMSSCROLL = 0x108,
//  STA_LOWPSNRESIPOTION = 0x109,
//  STA_NORPSNRESIPOTION = 0x10A,
//  STA_HIGHPSNRESIPOTION = 0x10B,
//  STA_LOWDSSRESIPOTION = 0x10C,
//  STA_NORDSSRESIPOTION = 0x10D,
//  STA_HIGHDSSRESIPOTION = 0x10E,
//  STA_LOWCURRESIPOTION = 0x10F,
//  STA_NORCURRESIPOTION = 0x110,
//  STA_HIGHCURRESIPOTION = 0x111,
//  STA_ALLCURRESIPOTION = 0x112,
//  STA_ALLDSSRESIPOTION = 0x113,
//  STA_ALLPSNRESIPOTION = 0x114,
//  STA_LOWMSSCROLL = 0x115,
//  STA_HIGHMSSCROLL = 0x116,
//  STA_BESTMSSCROLL = 0x117,
//  STA_BESTLOWMSSCROLL = 0x118,
//  STA_RAMAPOTION01 = 0x119,
//  STA_RAMAPOTION02 = 0x11A,
//  STA_RAMAPOTION03 = 0x11B,
//  STA_RAMAPOTION04 = 0x11C,
//  STA_RAMAPOTION05 = 0x11D,
//  STA_RAMAPOTION06 = 0x11E,
//  STA_RAMAPOTION07 = 0x11F,
//  STA_GMHIDEMODE = 0x120,
//  STA_OBSERVERHIDEMODE = 0x121,
//  STA_QUESTENTANGLE = 0x122,
//  STA_IMMORTAL = 0x123,
//  STA_KEEPFROMCHAT = 0x124,
//  STA_WEDDINGBUFF = 0x125,
//  STA_WEDDINGSUB01 = 0x126,
//  STA_WEDDINGSUB02 = 0x127,
//  STA_SOLEFIRE = 0x128,
//  STA_ACAMSBUF10PMAIN = 0x129,
//  STA_ACAMSBUF10P = 0x12A,
//  STA_ACAMSBUF7PMAIN = 0x12B,
//  STA_ACAMSBUF7P = 0x12C,
//  STA_ACAGENALBUF = 0x12D,
//  STA_NATURALENEMY = 0x12E,
//  STA_KALBANPOISON = 0x12F,
//  STA_KALBANDISEASE = 0x130,
//  STA_KALBANSTUN = 0x131,
//  STA_COMMONSTUN01 = 0x132,
//  STA_COMMONSTUN02 = 0x133,
//  STA_COMMONSTUN03 = 0x134,
//  STA_COMMONSTUN04 = 0x135,
//  STA_COMMONSTUN05 = 0x136,
//  STA_COMMONSTUN06 = 0x137,
//  STA_COMMONSTUN07 = 0x138,
//  STA_COMMONSTUN08 = 0x139,
//  STA_COMMONSTUN09 = 0x13A,
//  STA_COMMONSTUN10 = 0x13B,
//  STA_COMMONFEAR01 = 0x13C,
//  STA_COMMONFEAR02 = 0x13D,
//  STA_COMMONFEAR03 = 0x13E,
//  STA_COMMONFEAR04 = 0x13F,
//  STA_COMMONFEAR05 = 0x140,
//  STA_COMMONFEAR06 = 0x141,
//  STA_COMMONFEAR07 = 0x142,
//  STA_COMMONFEAR08 = 0x143,
//  STA_COMMONFEAR09 = 0x144,
//  STA_COMMONFEAR10 = 0x145,
//  STA_ETHEREAL = 0x146,
//  STA_GLDRESTORE = 0x147,
//  STA_GLDMOVESPEEDUP = 0x148,
//  STA_GLDACMINUS = 0x149,
//  STA_GLDSLOW = 0x14A,
//  STA_GLDSTUN = 0x14B,
//  STA_KARENDOT = 0x14C,
//  STA_KARENDIVINE = 0x14D,
//  STA_KARENSTATIC = 0x14E,
//  STA_KARENCAPTIVATE = 0x14F,
//  STA_ROCKCANTHEAL = 0x150,
//  STA_ROCKCANTCHAT = 0x151,
//  STA_ROCKDASHSTUN = 0x152,
//  STA_KARENDOTHEAL = 0x153,
//  STA_KARENSTUN = 0x154,
//  STA_MRMINUS = 0x155,
//  STA_SILBERKBLOODING = 0x156,
//  STA_BLOODFEAR = 0x157,
//  STA_GLDATKUP = 0x158,
//  STA_RESTEXP = 0x159,
//  STA_KNOCKBACK = 0x15A,
//  STA_KNOCKBACKFLY = 0x15B,
//  STA_KNOCKBACKROLL = 0x15C,
//  STA_FATALKNOCKBACK = 0x15D,
//  STA_CANNOTCONTROL = 0x15E,
//  STA_EVENTHPUP = 0x15F,
//  STA_EVENTSPUP = 0x160,
//  STA_EVENTALLSTATSUP = 0x161,
//  STA_EVENTSPEED = 0x162,
//  STA_EVENTACUP = 0x163,
//  STA_EVENTMRUP = 0x164,
//  STA_ANGRY = 0x165,
//  STA_PARALYSIS = 0x166,
//  STA_SPIRIT = 0x167,
//  STA_TIMEATTACK = 0x168,
//  STA_STAACREDDRAGON = 0x169,
//  STA_STAMRBLUEDRAGON = 0x16A,
//  STA_TIMEATTACKMINI = 0x16B,
//  STA_MONKEYSTUN = 0x16C,
//  STA_MONKEYDEFENSE = 0x16D,
//  STA_GTIRATEPOINT = 0x16E,
//  STA_GTISPEED = 0x16F,
//  STA_GTIRESISTALL = 0x170,
//  STA_GTIREFLECT = 0x171,
//  STA_GTIBLIND = 0x172,
//  STA_GTICONFUSION = 0x173,
//  STA_GTIMETASLIME = 0x174,
//  STA_GTIHIDE = 0x175,
//  STA_GTISCAN = 0x176,
//  STA_GTIBINDING = 0x177,
//  STA_GTIBOMB1 = 0x178,
//  STA_GTIBOMB2 = 0x179,
//  STA_GTIBOMBDIE = 0x17A,
//  STA_GTIREVERSEORDER = 0x17B,
//  STA_GTIVIRUSRT = 0x17C,
//  STA_GTIVIRUSMOVE = 0x17D,
//  STA_GTIMOBSUICIDE = 0x17E,
//  STA_GTIKNOCKBACKROLL = 0x17F,
//  STA_CRACKERACDOWN = 0x180,
//  STA_CRACKERWCDOWN = 0x181,
//  STA_CRACKERDISEASE = 0x182,
//  STA_CRACKERCURSE = 0x183,
//  STA_CRACKERWCUPRATE = 0x184,
//  STA_CRACKERACUPRATE = 0x185,
//  STA_HUMARACDOWNRATE = 0x186,
//  STA_BODYFORCE = 0x187,
//  STA_CANNOTCHANGETARGET = 0x188,
//  STA_SHADOWBINDING = 0x189,
//  STA_SOULFREE = 0x18A,
//  STA_NORTHPOISON = 0x18B,
//  STA_FITBLOOD = 0x18C,
//  STA_FITMOVEDOWN = 0x18D,
//  STA_NORTFBURN = 0x18E,
//  STA_RANGEEVASIONUP = 0x18F,
//  STA_POISONDMGADD = 0x190,
//  STA_POISONDMGDOWN = 0x191,
//  STA_BLOODDMGDOWN = 0x192,
//  STA_USESPADD = 0x193,
//  STA_DOTDMGDOWN = 0x194,
//  STA_EVASIONDOWN = 0x195,
//  STA_SHOCKSTUN = 0x196,
//  STA_DOTDMGADDALL = 0x197,
//  STA_SHOCKRUN = 0x198,
//  STA_KQSKELKNIGHTBLOODING = 0x199,
//  STA_MOBBURNTYPE01 = 0x19A,
//  STA_MOBSTUNTYPE01 = 0x19B,
//  STA_VACANT = 0x19C,
//  STA_WOLFCLAWTBUPRATE = 0x19D,
//  STA_ENTRAPBLN = 0x19E,
//  STA_ENTRAPMSD = 0x19F,
//  STA_ENTRAPBLD = 0x1A0,
//  STA_ENTRAPPLS = 0x1A1,
//  STA_QUESTENTANGLE2 = 0x1A2,
//  STA_GBGAMEMEMBERFULL = 0x1A3,
//  STA_MULTIBLOOD = 0x1A4,
//  STA_CHRTITLEWCUPRATE = 0x1A5,
//  STA_CHRTITLEWCDOWNRATE = 0x1A6,
//  STA_CHRTITLEMAUPRATE = 0x1A7,
//  STA_CHRTITLEMADOWNRATE = 0x1A8,
//  STA_CHRTITLEACUPRATE = 0x1A9,
//  STA_CHRTITLEACDOWNRATE = 0x1AA,
//  STA_CHRTITLEMRUPRATE = 0x1AB,
//  STA_CHRTITLEMRDOWNRATE = 0x1AC,
//  STA_CHRTITLEHPUPRATE = 0x1AD,
//  STA_CHRTITLEHPDOWNRATE = 0x1AE,
//  STA_CHRTITLEHPRESTORE = 0x1AF,
//  STA_CHRTITLESPUPRATE = 0x1B0,
//  STA_CHRTITLESPRESTORE = 0x1B1,
//  STA_CHRTITLETHUPRATE = 0x1B2,
//  STA_CHRTITLETHDOWNRATE = 0x1B3,
//  STA_CHRTITLETBUPRATE = 0x1B4,
//  STA_CHRTITLETBDOWNRATE = 0x1B5,
//  STA_CHRTITLESPEEDUPRATE = 0x1B6,
//  STA_CHRTITLESPEEDDOWNRATE = 0x1B7,
//  STA_CHRTITLECRITICALUPRATE = 0x1B8,
//  STA_CHRTITLEBLOODING = 0x1B9,
//  STA_MOBAPU01 = 0x1BA,
//  STA_BH_HELGA_NONE = 0x1BB,
//  STA_HELGBALL = 0x1BC,
//  STA_BH_KARATEMPLER_NONE = 0x1BD,
//  STA_BH_HELGAAPU01 = 0x1BE,
//  STA_BH_HELGADRT01 = 0x1BF,
//  STA_BH_HELGA_IDLE01 = 0x1C0,
//  STA_MOBACPLUS = 0x1C1,
//  STA_MOBSTN01 = 0x1C2,
//  STA_MOBPSN01 = 0x1C3,
//  STA_MOBOPU01 = 0x1C4,
//  STA_MOBMSD02 = 0x1C5,
//  STA_MOBSLC01 = 0x1C6,
//  STA_MOBBLD01 = 0x1C7,
//  STA_MOBMTS01 = 0x1C8,
//  STA_MOBBRN01 = 0x1C9,
//  STA_MOBMSD01 = 0x1CA,
//  STA_ADLUBAUP = 0x1CB,
//  STA_ADLUBADOWN = 0x1CC,
//  STA_BURNPAINME = 0x1CD,
//  STA_BURNPAINFOE = 0x1CE,
//  STA_GROUNDSTRIKE = 0x1CF,
//  STA_BOMBSHOT = 0x1D0,
//  STA_CROSSDROP = 0x1D1,
//  STA_METEOR = 0x1D2,
//  STA_MAGICDANCEUSESPDOWN = 0x1D3,
//  STA_DEEPFEARMENDOWNRATE = 0x1D4,
//  STA_MENDOWNRATE = 0x1D5,
//  STA_SHAMECRIUP = 0x1D6,
//  STA_MOBMRS01 = 0x1D7,
//  STA_MOBACS01 = 0x1D8,
//  STA_NOTTARGET = 0x1D9,
//  STA_MAGICDANCEUSESPDOWN02 = 0x1DA,
//  STA_MAGICDANCEUSESPDOWN03 = 0x1DB,
//  STA_MAGICDANCEUSESPDOWN04 = 0x1DC,
//  STA_MAGICDANCEUSESPDOWN05 = 0x1DD,
//  STA_MENDOWNRATE02 = 0x1DE,
//  STA_MENDOWNRATE03 = 0x1DF,
//  STA_MENDOWNRATE04 = 0x1E0,
//  STA_MENDOWNRATE05 = 0x1E1,
//  STA_SHAMECRIUP02 = 0x1E2,
//  STA_SHAMECRIUP03 = 0x1E3,
//  STA_SHAMECRIUP04 = 0x1E4,
//  STA_SHAMECRIUP05 = 0x1E5,
//  STA_SNSATKUP = 0x1E6,
//  STA_SNSCRIUP = 0x1E7,
//  STA_SNSDEFENSEUP = 0x1E8,
//  STA_SNSHPUP = 0x1E9,
//  STA_SNSSPUP = 0x1EA,
//  STA_SNSSPEEDUP = 0x1EB,
//  STA_MULTIHEAL = 0x1EC,
//  STA_HIDEWC = 0x1ED,
//  STA_EGLACK04 = 0x1EE,
//  STA_EGLACKMAD05 = 0x1EF,
//  STA_SALARE04 = 0x1F0,
//  STA_SALARE00 = 0x1F1,
//  STA_ADLFLOUSSIER = 0x1F2,
//  STA_ADLFLOUSSIERIMT = 0x1F3,
//  STA_ADLFSTUN = 0x1F4,
//  STA_EGLACKMAD04 = 0x1F5,
//  STA_MINEICE = 0x1F6,
//  STA_MINESTUN = 0x1F7,
//  STA_MINEFIREVIVI = 0x1F8,
//  STA_MINEICEVIVI = 0x1F9,
//  STA_MINEREWARD = 0x1FA,
//  STA_SETF2WCUP = 0x1FB,
//  STA_SETF2ACUP = 0x1FC,
//  STA_SETF4HPUP = 0x1FD,
//  STA_SETF4ACDOWN = 0x1FE,
//  STA_SETF4ACUP = 0x1FF,
//  STA_SETF4WCUPRATE = 0x200,
//  STA_SETF4ACUPRATE = 0x201,
//  STA_SETA2WCUP = 0x202,
//  STA_SETA4SPEEDUP = 0x203,
//  STA_SETA4SPEEDDOWN = 0x204,
//  STA_SETA4ATKSPEEDUP = 0x205,
//  STA_SETM2MAUP = 0x206,
//  STA_SETM2MRUP = 0x207,
//  STA_SETM3SPUP = 0x208,
//  STA_SETM4MAUP = 0x209,
//  STA_SETM4MRDOWN = 0x20A,
//  STA_SETM4SPUP = 0x20B,
//  STA_SETM4MRUP = 0x20C,
//  STA_SETC2WCUP = 0x20D,
//  STA_SETC2MAUP = 0x20E,
//  STA_SETC3MRUP = 0x20F,
//  STA_SETC4MRUP = 0x210,
//  STA_SETC4WCUP = 0x211,
//  STA_SETC4ATKDOWN = 0x212,
//  STA_SETC4ACUP = 0x213,
//  STA_SETC4ACDOWN = 0x214,
//  STA_SETC4MAUP = 0x215,
//  STA_SETJ2WCUP = 0x216,
//  STA_SETJ2HPUP = 0x217,
//  STA_SETJ3SPUP = 0x218,
//  STA_SETJ4ACDOWN = 0x219,
//  STA_SETJ4ATKSPPEUP = 0x21A,
//  STA_SETJ4CRLUP = 0x21B,
//  STA_SETJ4WCUP = 0x21C,
//  STA_ENWCUP = 0x21D,
//  STA_ENMAUP = 0x21E,
//  STA_ENATKSPEED = 0x21F,
//  STA_ENWCRATE = 0x220,
//  STA_ENADDDMGRATE = 0x221,
//  STA_ENKNOCKBACKRATE = 0x222,
//  STA_ENBINDINGRATE = 0x223,
//  STA_ENMOVEDOWNRATE = 0x224,
//  STA_QDAYWCUP = 0x225,
//  STA_QDAYMAUP = 0x226,
//  STA_QDAYEXPUP = 0x227,
//  STA_QDAYDROPUP = 0x228,
//  STA_SWICEWARN = 0x229,
//  STA_SURPRISE = 0x22A,
//  STA_SWPLSWARN = 0x22B,
//  STA_SWSTNWARN = 0x22C,
//  STA_SWBRN01WARN = 0x22D,
//  STA_SWLVTWARN = 0x22E,
//  STA_AWAYBACKSPOT = 0x22F,
//  STA_RADIONBUFF = 0x230,
//  STA_AIRIBUFF = 0x231,
//  STA_WARLBRAINWASH = 0x232,
//  STA_WARLBRN01 = 0x233,
//  STA_STUNCANATTACK = 0x234,
//  STA_TRANSFORM = 0x235,
//  STA_BALLSNOW = 0x236,
//  STA_SNOWMAN = 0x237,
//  STA_WARNSETBUFF = 0x238,
//  STA_SET_VALEN_STN = 0x239,
//  STA_SET_VALEN_Heal = 0x23A,
//  STA_VALEN_REWARD = 0x23B,
//  STA_KQEGG_SPDW = 0x23C,
//  STA_KQEGG_REWARD = 0x23D,
//  STA_KQEGG_SPUP = 0x23E,
//  STA_KQSPRING_FEAR = 0x23F,
//  STA_KQSPRING_SLOW = 0x240,
//  STA_KQ_SPUP_BUFF = 0x241,
//  STA_KQ_SPIM_BUFF = 0x242,
//  STA_KQ_SPUP_RATE_BUFF = 0x243,
//  STA_KQSPRING_ARROW = 0x244,
//  STA_WARHBRN01 = 0x245,
//  STA_WARHBRN = 0x246,
//  STA_STRONGER_RANGEATTACK = 0x247,
//  STA_STRONGER_MELEEATTACK = 0x248,
//  STA_FLAMINGBODY = 0x249,
//  STA_COUNT30 = 0x24A,
//  STA_WARHWPNBRN = 0x24B,
//  STA_ORBATKRATEUP = 0x24C,
//  STA_RECOUP = 0x24D,
//  STA_LIGHTTOUCH = 0x24E,
//  STA_TREAT = 0x24F,
//  STA_LIGHTMARK = 0x250,
//  STA_MINHP = 0x251,
//  STA_MOONLIGHT = 0x252,
//  STA_LPDOTPLUS = 0x253,
//  STA_DMGSHIELD = 0x254,
//  STA_DELCASTTIME = 0x255,
//  STA_SETS2WCMAUP = 0x256,
//  STA_SETS2ACMRUP = 0x257,
//  STA_SETS4WCMAUP = 0x258,
//  STA_SETS4ACMRUP = 0x259,
//  STA_SENPARTYHPUPMAIN = 0x25A,
//  STA_SENPARTYHPUP = 0x25B,
//  STA_SENPARTYHPUP1 = 0x25C,
//  STA_SENEVENTEXPUP = 0x25D,
//  STA_SENEVENTDROPUP = 0x25E,
//  STA_PZL_HIDE = 0x25F,
//  STA_PZL_OCCUPY = 0x260,
//  STA_PZL_REWARD_S = 0x261,
//  STA_PZL_REWARD_H = 0x262,
//  STA_PZL_REWARD_SH1 = 0x263,
//  STA_PZL_REWARD_SH2 = 0x264,
//  STA_ROUTMAGEATKUP = 0x265,
//  STA_ARK_STN = 0x266,
//  STA_ARK_BLD01 = 0x267,
//  STA_ARK_BLD02 = 0x268,
//  STA_ARK_BLD03 = 0x269,
//  STA_ARK_BRN01 = 0x26A,
//  STA_ARK_BRN02 = 0x26B,
//  STA_ARK_BRN03 = 0x26C,
//  STA_ARK_THDOWN01 = 0x26D,
//  STA_ARK_THDOWN02 = 0x26E,
//  STA_KAHAL_STN = 0x26F,
//  STA_KAHAL_BLD = 0x270,
//  STA_KAHAL_FEAR01 = 0x271,
//  STA_KAHAL_FEAR02 = 0x272,
//  STA_KAHAL_SHOUT = 0x273,
//  STA_KAHAL_SPDDOWN = 0x274,
//  STA_KAHAL_ICE = 0x275,
//  STA_SIREN_STN1 = 0x276,
//  STA_SIREN_STN2 = 0x277,
//  STA_SIREN_NOMOVE = 0x278,
//  STA_SIREN_KNOCKBACK1 = 0x279,
//  STA_SIREN_KNOCKBACK2 = 0x27A,
//  STA_SIREN_HEAL = 0x27B,
//  STA_SIREN_LVT1 = 0x27C,
//  STA_SIREN_LVT2 = 0x27D,
//  STA_SIREN_BLD01 = 0x27E,
//  STA_SIREN_FEAR = 0x27F,
//  STA_SIREN_BLD02 = 0x280,
//  STA_CONHPPOTION_T6 = 0x281,
//  STA_CONSPPOTION_T6 = 0x282,
//  STA_DEXPOTION_T6 = 0x283,
//  STA_ACMRPOTION_T6 = 0x284,
//  STA_STRCRIPOTION_T6 = 0x285,
//  STA_PSNRESIPOTION_T6 = 0x286,
//  STA_DSSRESIPOTION_T6 = 0x287,
//  STA_CURRESIPOTION_T6 = 0x288,
//  STA_THSCROLL_T6 = 0x289,
//  STA_TBSCROLL_T6 = 0x28A,
//  STA_MRSCROLL_T6 = 0x28B,
//  STA_ACSCROLL_T6 = 0x28C,
//  STA_CRISCROLL_T6 = 0x28D,
//  STA_MAXHPSCROLL_T6 = 0x28E,
//  STA_MAXSPSCROLL_T6 = 0x28F,
//  STA_MSSCROLL_T6 = 0x290,
//  STA_BERVALE_ICE01 = 0x291,
//  STA_BERVALE_ICE02 = 0x292,
//  STA_BERVALE_BLD01 = 0x293,
//  STA_BERVALE_BLD02 = 0x294,
//  STA_B_ALBI_BRN = 0x295,
//  STA_B_ALBI_KNOCK = 0x296,
//  STA_B_ALBI_STN = 0x297,
//  STA_B_ALBI_FEAR = 0x298,
//  STA_B_ALBI_DOT = 0x299,
//  STA_B_ALBI_REFLECT = 0x29A,
//  STA_B_ALBI_ACMRUP = 0x29B,
//  STA_ADLFGCRAZY = 0x29C,
//  STA_FCITRIEDOT = 0x29D,
//  STA_LCWCMAUP = 0x29E,
//  STA_E_SLIME = 0x29F,
//  STA_E_HONEYING = 0x2A0,
//  STA_E_PHINO = 0x2A1,
//  STA_E_LIZARDMAN = 0x2A2,
//  STA_E_KINGCRAB = 0x2A3,
//  STA_E_SPARKDOG = 0x2A4,
//  STA_E_LAVAVIVI = 0x2A5,
//  STA_E_PHINOFLIE = 0x2A6,
//  STA_E_MUSHROOM = 0x2A7,
//  STA_E_SPIDER = 0x2A8,
//  STA_E_B_CRACKERHUMAR = 0x2A9,
//  STA_E_HELGA = 0x2AA,
//  STA_EMP_STUN = 0x2AB,
//  STA_EMP_KINGBLOODING = 0x2AC,
//  STA_EMP_EMPBLOODING = 0x2AD,
//  STA_EMP_LVT = 0x2AE,
//  STA_LCACMRUP = 0x2AF,
//  STA_E_FIREWORKS = 0x2B0,
//  STA_ARENA_SPDUP = 0x2B1,
//  STA_ARENA_STUN = 0x2B2,
//  STA_ARENA_DRAGOUT = 0x2B3,
//  STA_ARENA_DEFDW = 0x2B4,
//  STA_ARENA_SPDDW = 0x2B5,
//  STA_ARENA_ALLDW = 0x2B6,
//  STA_ARENA_REWARD = 0x2B7,
//  STA_ARENA_FLAG_RED = 0x2B8,
//  STA_ARENA_FLAG_BLUE = 0x2B9,
//  STA_ARENA_MINHP = 0x2BA,
//  STA_X_ICE = 0x2BB,
//  STA_X_SNOWMAN = 0x2BC,
//  STA_X_REWARD01 = 0x2BD,
//  STA_X_REWARD02 = 0x2BE,
//  STA_X_REWARD03 = 0x2BF,
//  STA_X_REWARD04 = 0x2C0,
//  STA_E_SKI_ICE = 0x2C1,
//  STA_E_SKI_SPEEDUP = 0x2C2,
//  STA_E_SKI_REWARD = 0x2C3,
//  STA_E_SKI_STUN = 0x2C4,
//  STA_LAB_PURYIMPACTSTUN = 0x2C5,
//  STA_C_PURYIMPACTSTUN = 0x2C6,
//  STA_E_EGG2014_HOSHEMING = 0x2C7,
//  STA_E_EGG2014_SELFREVIVE = 0x2C8,
//  STA_E_EGG2014_EXPUP = 0x2C9,
//  STA_E_EGG2014_DROPRATEUP = 0x2CA,
//  STA_MOVERSTATUPSINGLE = 0x2CB,
//  STA_MOVERSTATUPPARTY = 0x2CC,
//  STA_MOVERSTATUP = 0x2CD,
//  STA_KDSOCCER_SPEED_UP = 0x2CE,
//  STA_KDSOCCER_INVINCIBLE = 0x2CF,
//  STA_KQWATER_ARROW_BLUE = 0x2D0,
//  STA_KQWATER_ARROW_RED = 0x2D1,
//  STA_E_JACKO = 0x2D2,
//  STA_E_KEBING = 0x2D3,
//  STA_E_FORASCHIEF = 0x2D4,
//  STA_E_H_WIN_SPEEDUP = 0x2D5,
//  STA_E_H_WIN_SPEEDDOWN = 0x2D6,
//  STA_ADLFLOUSSIER_H = 0x2D7,
//  STA_E_USER_NEWBIE01 = 0x2D8,
//  STA_E_USER_NEWBIE02 = 0x2D9,
//  STA_E_USER_NEWBIE03 = 0x2DA,
//  STA_E_USER_NEWBIE04 = 0x2DB,
//  STA_E_USER_NEWBIE05 = 0x2DC,
//  STA_E_USER_COMEBACK_MAIN01 = 0x2DD,
//  STA_E_USER_COMEBACK_MAIN02 = 0x2DE,
//  STA_E_USER_COMEBACK_MAIN03 = 0x2DF,
//  STA_E_USER_COMEBACK_MAIN04 = 0x2E0,
//  STA_E_USER_COMEBACK_MAIN05 = 0x2E1,
//  STA_E_USER_COMEBACK01 = 0x2E2,
//  STA_E_USER_COMEBACK02 = 0x2E3,
//  STA_E_USER_COMEBACK03 = 0x2E4,
//  STA_E_USER_COMEBACK04 = 0x2E5,
//  STA_E_USER_COMEBACK05 = 0x2E6,
//  STA_XMAS_STATUP = 0x2E7,
//  STA_IDBUFF_100 = 0x2E8,
//  STA_IDBUFF_80 = 0x2E9,
//  STA_IDBUFF_60 = 0x2EA,
//  STA_IDBUFF_40 = 0x2EB,
//  STA_IDBUFF_20 = 0x2EC,
//  STA_E_SNOWMANR = 0x2ED,
//  STA_E_SNOWMANB = 0x2EE,
//  STA_KDFARGELS_BLOOD01 = 0x2EF,
//  STA_KDFARGELS_BLOOD02 = 0x2F0,
//  STA_KDFARGELS_BLOOD03 = 0x2F1,
//  STA_KDFARGELS_MRDOWNRATE = 0x2F2,
//  STA_KDFARGELS_AIRBORNE = 0x2F3,
//  STA_KDFARGELS_ACMRDOWN = 0x2F4,
//  STA_KDFARGELS_DMGNEGLECT = 0x2F5,
//  STA_KDFARGELS_DOTHEAL = 0x2F6,
//  STA_SDVALE01_STN = 0x2F7,
//  STA_SDVALE01_WHEEL = 0x2F8,
//  STA_SDVALE01_SPDUP = 0x2F9,
//  STA_SDVALE01_SPDDOWN = 0x2FA,
//  STA_SDVALE01_BLIND = 0x2FB,
//  STA_SDVALE01_PSN = 0x2FC,
//  STA_SDVALE01_ICEFIELD = 0x2FD,
//  STA_SDVALE01_BRN = 0x2FE,
//  STA_SDVALE01_WCMAUP = 0x2FF,
//  STA_SDVALE01_KNOCK = 0x300,
//  STA_COSMUSAACRATE = 0x301,
//  STA_COSMUSACRI = 0x302,
//  STA_COSMUSAALLSTAT = 0x303,
//  STA_BH_ALBI_REFLECT = 0x304,
//  STA_BH_ALBI_ACMRUP = 0x305,
//  STA_E_ZOMBIE = 0x306,
//  STA_E_MARACREW = 0x307,
//  STA_E_MARAELITE = 0x308,
//  STA_E_MARASAILOR = 0x309,
//  STA_E_PSYKEN = 0x30A,
//  STA_E_PSYKENDOG = 0x30B,
//  STA_E_MEGAN = 0x30C,
//  STA_E_YETI = 0x30D,
//  STA_E_IMP = 0x30E,
//  STA_E_ROBO = 0x30F,
//  STA_E_HOB = 0x310,
//  STA_E_PINKY = 0x311,
//  STA_E_WARH_DEVILDOM = 0x312,
//  STA_E_ARKNOVICE = 0x313,
//  STA_E_ARKTECH = 0x314,
//  STA_E_MANDRAGORA = 0x315,
//  STA_E_S_HAYREDDIN = 0x316,
//  STA_E_MARA = 0x317,
//  STA_BHKARENDOT = 0x318,
//  STA_BHKARENDIVINE = 0x319,
//  STA_BHKARENSTATIC = 0x31A,
//  STA_BHKARENCAPTIVATE = 0x31B,
//  STA_BHKARENDOTHEAL = 0x31C,
//  STA_BHKARENSTUN = 0x31D,
//  STA_BHKARENREF = 0x31E,
//  STA_GCGCAST = 0x31F,
//  STA_SCGATK = 0x320,
//  STA_STONEATK = 0x321,
//  STA_COLL_BLOOD = 0x322,
//  STA_COLL_ACID = 0x323,
//  STA_COLL_KNOCK_01 = 0x324,
//  STA_COLL_AIRBORNE = 0x325,
//  STA_COLL_STUN_01 = 0x326,
//  STA_COLL_STUN_02 = 0x327,
//  STA_COLL_FEAR = 0x328,
//  STA_COLL_HEAL = 0x329,
//  STA_COLL_STUN_03 = 0x32A,
//  STA_BLA_ACMDOWN = 0x32B,
//  STA_BLA_DOT = 0x32C,
//  STA_BLA_KNOCK = 0x32D,
//  STA_BLA_FEAR = 0x32E,
//  STA_BLA_LVT = 0x32F,
//  STA_BLA_STN = 0x330,
//  STA_BLA_ACRATE = 0x331,
//  STA_TGGUARDIANBALL = 0x332,
//  STA_TGHAMMER = 0x333,
//  STA_TGROAR = 0x334,
//  STA_TGDOT = 0x335,
//  MAX_ABSTATEINDEX = 0x336,
//};
type AbStateIndex uint32

//noinspection ALL
const (
	StaSeverBone AbStateIndex = iota
	StaRedSlash
	StaBattleBlowStun
	StaMightySoulMain
	StaMightySoul
	StaMoraleDecreaseWc
	StaSpeedShield
	StaHarmDefect
	StaBerserkFrenzy
	StaShockBladeStun
	StaMightySoul2
	StaMightySoul3
	StaMightySoul4
	StaMightySoul5
	StaViolence
	StaBuckler
	StaNeglect
	StaBreak
	StaBlessingMain
	StaBlessing
	StaSafeProtection
	StaPsychicBluntStun
	StaPsychicChopBlood
	StaDarknessProtection
	StaRestore
	StaHitProtection
	StaMentalShoutMain
	StaMentalShout
	StaDivineShield
	StaDivineWeaponWcMain
	StaDivineWeaponWc
	StaSacrifice
	StaCrossCastingCoolTime
	StaPanicForceMr
	StaReverseOrder
	StaHorrorForceStr
	StaBlessing2
	StaBlessing3
	StaBlessing4
	StaBlessing5
	StaMentalShout2
	StaMentalShout3
	StaMentalShout4
	StaMentalShout5
	StaDivineWeaponWc2
	StaDivineWeaponWc3
	StaDivineWeaponWc4
	StaDivineWeaponWc5
	StaRebirth
	StaDeadlyBlessing
	StaDodge
	StaFuryImpactStun
	StaForestWind
	StaWindChargeMain
	StaWindCharge
	StaBoneArrow
	StaSpiritThornEntangle
	// ooof x.x i wonder if i should respect golang conventions
	StaPoisonshot
	StaBiteArrow
	StaMistChargeMain
	StaMistCharge
	StaSpiritFog
	StaHawkTalonAtkSpeed
	StaNaturecastingcooltime
	StaPiercingguard
	StaShockscreamwc
	StaStingeruptionslow
	StaWindcharge2
	StaWindcharge3
	StaWindCharge4
	StaWindCharge5
	StaMistCharge2
	StaMistCharge3
	StaMistCharge4
	StaMistCharge5
	StaHide
	StaBlind
	StaEntraphide
	StaIcebolt
	StaLightningbolt
	StaBlur
	StaSoulEdge
	STA_RINGSHIELD
	STA_ICEBLASTSTUN
	STA_CHAINLIGHTNINGSTUN
	STA_DRAINMINDFEAR
	STA_CHAINCASTINGCOOLTIME
	STA_CURSEMAGICCASTIME
	STA_FROSTNOVA
	STA_THUNDERBOLT
	STA_SOULEDGEMAIN
	STA_SOULEDGE2
	STA_SOULEDGE3
	STA_SOULEDGE4
	STA_SOULEDGE5
	STA_DEEPER
	STA_MESMERIZE
	STA_POLYMORPH
	STA_ICEFIELD
	STA_MARASTUN
	STA_KINGSLIMEBLOODING
	STA_MARLONEENTANGLE
	STA_NOXENTANGLE
	STA_SKELKNIGHTBLOODING
	STA_ROBOACPLUS
	STA_GOKINGSTUN
	STA_GOKINGSTRRATE
	STA_KINGCALLACPLUS
	STA_GHKNIGHTENTANGLE
	STA_HUNGRYWOLFBLOODING
	STA_KQSKELKNIGHTENTANGLE
	STA_MARLONECAPTAINATKSPD
	STA_ARCHMAGEBOOKSTUN
	STA_GHOSTFEAR
	STA_KQ_BOSSROBOFEAR
	STA_KQ_BOSSROBO2FEAR
	STA_NOXSK2BLOODING
	STA_KQ_G_TBRAIDERCURSE
	STA_ELFKNIGHTSOULDEXCURSE
	STA_JOKERTRUMPYTHCURSE
	STA_KEBINGCURSE
	STA_KINGCRABCURSE
	STA_NAVARCURSE
	STA_MARACURSE
	STA_SKELWARRIORCURSE
	STA_ARCHMAGEBOOKCURSE
	STA_KARATEMPLERCURSE
	STA_SMARTPHINOCURSE
	STA_MARLONESOLDIERCURSE
	STA_OLDFOXCURSE
	STA_GOBLINMAGECURSE
	STA_HARKANCURSE
	STA_DISHARKANCURSE
	STA_STONIECURSE
	STA_OGRECURSE
	STA_MARASAILORCURSE
	STA_OLDARCHONCURSE
	STA_KINGMUSHROOMCURSE
	STA_BCTRUMPYCURSE
	STA_KQ_K_BOSSPHINOCURSE
	STA_KQ_K_PHINOFLIECURSE
	STA_TORTURERBLOODING
	STA_SHARPBOARBLOODING
	STA_FOBLOODING
	STA_BABYWEREBEARBLOODING
	STA_SENIORTORTURERBLOODING
	STA_JEWELKEEPERBLOODING
	STA_SHYLPHBLOODING
	STA_SGTRUMPYBLOODING
	STA_KQ_K_SOLIDERBLOODING
	STA_SKELKNIGHTDISEASE
	STA_MOB1SLOW
	STA_MOB2SLOW
	STA_MOB3SLOW
	STA_MOB4SLOW
	STA_MOB5SLOW
	STA_MOB1STUN
	STA_MOB2STUN
	STA_MOB3STUN
	STA_MOB4STUN
	STA_MOB5STUN
	STA_KQMARASTUN
	STA_KQGOBLEKINGSTUN
	STA_DIAMASTERSTUN
	STA_ANCIENTSTONIESTUN
	STA_MOB1ENTANGLE
	STA_MOB2ENTANGLE
	STA_MOB3ENTANGLE
	STA_MOB4ENTANGLE
	STA_MOB5ENTANGLE
	STA_KQMARLONEENTANGLE
	STA_LEGENDARYTREEENTANGLE
	STA_GIANTELVENTREEENTANGLE
	STA_MOB1POISON
	STA_MOB2POISON
	STA_MOB3POISON
	STA_MOB4POISON
	STA_MOB5POISON
	STA_MOB6POISON
	STA_DIATRUMPYPOISON
	STA_MOB1DISEASE1
	STA_MOB2DISEASE1
	STA_MOB3DISEASE1
	STA_MOB4DISEASE1
	STA_MOB5DISEASE1
	STA_MOB6DISEASE1
	STA_MOB1DISEASE2
	STA_MOB2DISEASE2
	STA_MOB3DISEASE2
	STA_MOB4DISEASE2
	STA_MOB5DISEASE2
	STA_MOB6DISEASE2
	STA_MOB1DISEASE3
	STA_MOB2DISEASE3
	STA_MOB3DISEASE3
	STA_MOB4DISEASE3
	STA_MOB5DISEASE3
	STA_MOB6DISEASE3
	STA_MOBIMMORTAL
	STA_MOBINVISIBLE
	STA_MOBMRPLUS
	STA_ACMODE
	STA_MRMODE
	STA_HELGAACMINUS
	STA_BESTLOWCONHPPOTION
	STA_LOWCONHPPOTION
	STA_NORCONHPPOTION
	STA_HIGHCONHPPOTION
	STA_BESTHIGHCONHPPOTION
	STA_BESTLOWCONSPPOTION
	STA_LOWCONSPPOTION
	STA_NORCONSPPOTION
	STA_HIGHCONSPPOTION
	STA_BESTHIGHCONSPPOTION
	STA_BESTLOWTHSCROLL
	STA_LOWTHSCROLL
	STA_NORTHSCROLL
	STA_HIGHTHSCROLL
	STA_BESTHIGHTHSCROLL
	STA_BESTLOWTBSCROLL
	STA_LOWTBSCROLL
	STA_NORTBSCROLL
	STA_HIGHTBSCROLL
	STA_BESTHIGHTBSCROLL
	STA_BESTLOWMRSCROLL
	STA_LOWMRSCROLL
	STA_NORMRSCROLL
	STA_HIGHMRSCROLL
	STA_BESTHIGHMRSCROLL
	STA_BESTLOWACSCROLL
	STA_LOWACSCROLL
	STA_NORACSCROLL
	STA_HIGHACSCROLL
	STA_BESTHIGHACSCROLL
	STA_BESTLOWCRISCROLL
	STA_LOWCRISCROLL
	STA_NORCRISCROLL
	STA_HIGHCRISCROLL
	STA_BESTHIGHCRISCROLL
	STA_BESTLOWMAXHPSCROLL
	STA_LOWMAXHPSCROLL
	STA_NORMAXHPSCROLL
	STA_HIGHMAXHPSCROLL
	STA_BESTHIGHMAXHPSCROLL
	STA_BESTLOWMAXSPSCROLL
	STA_LOWMAXSPSCROLL
	STA_NORMAXSPSCROLL
	STA_HIGHMAXSPSCROLL
	STA_BESTHIGHMAXSPSCROLL
	STA_BESTLOWSTRCRISCROLL
	STA_LOWSTRCRISCROLL
	STA_NORSTRCRISCROLL
	STA_HIGHSTRCRISCROLL
	STA_BESTHIGHSTRCRISCROLL
	STA_BESTLOWDEXSCROLL
	STA_LOWDEXSCROLL
	STA_NORDEXSCROLL
	STA_HIGHDEXSCROLL
	STA_BESTHIGHDEXSCROLL
	STA_BESTLOWACMRSCROLL
	STA_LOWACMRSCROLL
	STA_NORACMRSCROLL
	STA_HIGHACMRSCROLL
	STA_BESTHIGHACMRSCROLL
	STA_NORMSSCROLL
	STA_LOWPSNRESIPOTION
	STA_NORPSNRESIPOTION
	STA_HIGHPSNRESIPOTION
	STA_LOWDSSRESIPOTION
	STA_NORDSSRESIPOTION
	STA_HIGHDSSRESIPOTION
	STA_LOWCURRESIPOTION
	STA_NORCURRESIPOTION
	STA_HIGHCURRESIPOTION
	STA_ALLCURRESIPOTION
	STA_ALLDSSRESIPOTION
	STA_ALLPSNRESIPOTION
	STA_LOWMSSCROLL
	STA_HIGHMSSCROLL
	STA_BESTMSSCROLL
	STA_BESTLOWMSSCROLL
	STA_RAMAPOTION01
	STA_RAMAPOTION02
	STA_RAMAPOTION03
	STA_RAMAPOTION04
	STA_RAMAPOTION05
	STA_RAMAPOTION06
	STA_RAMAPOTION07
	STA_GMHIDEMODE
	STA_OBSERVERHIDEMODE
	STA_QUESTENTANGLE
	STA_IMMORTAL
	STA_KEEPFROMCHAT
	STA_WEDDINGBUFF
	STA_WEDDINGSUB01
	STA_WEDDINGSUB02
	STA_SOLEFIRE
	STA_ACAMSBUF10PMAIN
	STA_ACAMSBUF10P
	STA_ACAMSBUF7PMAIN
	STA_ACAMSBUF7P
	STA_ACAGENALBUF
	STA_NATURALENEMY
	STA_KALBANPOISON
	STA_KALBANDISEASE
	STA_KALBANSTUN
	STA_COMMONSTUN01
	STA_COMMONSTUN02
	STA_COMMONSTUN03
	STA_COMMONSTUN04
	STA_COMMONSTUN05
	STA_COMMONSTUN06
	STA_COMMONSTUN07
	STA_COMMONSTUN08
	STA_COMMONSTUN09
	STA_COMMONSTUN10
	STA_COMMONFEAR01
	STA_COMMONFEAR02
	STA_COMMONFEAR03
	STA_COMMONFEAR04
	STA_COMMONFEAR05
	STA_COMMONFEAR06
	STA_COMMONFEAR07
	STA_COMMONFEAR08
	STA_COMMONFEAR09
	STA_COMMONFEAR10
	STA_ETHEREAL
	STA_GLDRESTORE
	STA_GLDMOVESPEEDUP
	STA_GLDACMINUS
	STA_GLDSLOW
	STA_GLDSTUN
	STA_KARENDOT
	STA_KARENDIVINE
	STA_KARENSTATIC
	STA_KARENCAPTIVATE
	STA_ROCKCANTHEAL
	STA_ROCKCANTCHAT
	STA_ROCKDASHSTUN
	STA_KARENDOTHEAL
	STA_KARENSTUN
	STA_MRMINUS
	STA_SILBERKBLOODING
	STA_BLOODFEAR
	STA_GLDATKUP
	STA_RESTEXP
	STA_KNOCKBACK
	STA_KNOCKBACKFLY
	STA_KNOCKBACKROLL
	STA_FATALKNOCKBACK
	STA_CANNOTCONTROL
	STA_EVENTHPUP
	STA_EVENTSPUP
	STA_EVENTALLSTATSUP
	STA_EVENTSPEED
	STA_EVENTACUP
	STA_EVENTMRUP
	STA_ANGRY
	STA_PARALYSIS
	STA_SPIRIT
	STA_TIMEATTACK
	STA_STAACREDDRAGON
	STA_STAMRBLUEDRAGON
	STA_TIMEATTACKMINI
	STA_MONKEYSTUN
	STA_MONKEYDEFENSE
	STA_GTIRATEPOINT
	STA_GTISPEED
	STA_GTIRESISTALL
	STA_GTIREFLECT
	STA_GTIBLIND
	STA_GTICONFUSION
	STA_GTIMETASLIME
	STA_GTIHIDE
	STA_GTISCAN
	STA_GTIBINDING
	STA_GTIBOMB1
	STA_GTIBOMB2
	STA_GTIBOMBDIE
	STA_GTIREVERSEORDER
	STA_GTIVIRUSRT
	STA_GTIVIRUSMOVE
	STA_GTIMOBSUICIDE
	STA_GTIKNOCKBACKROLL
	STA_CRACKERACDOWN
	STA_CRACKERWCDOWN
	STA_CRACKERDISEASE
	STA_CRACKERCURSE
	STA_CRACKERWCUPRATE
	STA_CRACKERACUPRATE
	STA_HUMARACDOWNRATE
	STA_BODYFORCE
	STA_CANNOTCHANGETARGET
	STA_SHADOWBINDING
	STA_SOULFREE
	STA_NORTHPOISON
	STA_FITBLOOD
	STA_FITMOVEDOWN
	STA_NORTFBURN
	STA_RANGEEVASIONUP
	STA_POISONDMGADD
	STA_POISONDMGDOWN
	STA_BLOODDMGDOWN
	STA_USESPADD
	STA_DOTDMGDOWN
	STA_EVASIONDOWN
	STA_SHOCKSTUN
	STA_DOTDMGADDALL
	STA_SHOCKRUN
	STA_KQSKELKNIGHTBLOODING
	STA_MOBBURNTYPE01
	STA_MOBSTUNTYPE01
	STA_VACANT
	STA_WOLFCLAWTBUPRATE
	STA_ENTRAPBLN
	STA_ENTRAPMSD
	STA_ENTRAPBLD
	STA_ENTRAPPLS
	STA_QUESTENTANGLE2
	STA_GBGAMEMEMBERFULL
	STA_MULTIBLOOD
	STA_CHRTITLEWCUPRATE
	STA_CHRTITLEWCDOWNRATE
	STA_CHRTITLEMAUPRATE
	STA_CHRTITLEMADOWNRATE
	STA_CHRTITLEACUPRATE
	STA_CHRTITLEACDOWNRATE
	STA_CHRTITLEMRUPRATE
	STA_CHRTITLEMRDOWNRATE
	STA_CHRTITLEHPUPRATE
	STA_CHRTITLEHPDOWNRATE
	STA_CHRTITLEHPRESTORE
	STA_CHRTITLESPUPRATE
	STA_CHRTITLESPRESTORE
	STA_CHRTITLETHUPRATE
	STA_CHRTITLETHDOWNRATE
	STA_CHRTITLETBUPRATE
	STA_CHRTITLETBDOWNRATE
	STA_CHRTITLESPEEDUPRATE
	STA_CHRTITLESPEEDDOWNRATE
	STA_CHRTITLECRITICALUPRATE
	STA_CHRTITLEBLOODING
	STA_MOBAPU01
	STA_BH_HELGA_NONE
	STA_HELGBALL
	STA_BH_KARATEMPLER_NONE
	STA_BH_HELGAAPU01
	STA_BH_HELGADRT01
	STA_BH_HELGA_IDLE01
	STA_MOBACPLUS
	STA_MOBSTN01
	STA_MOBPSN01
	STA_MOBOPU01
	STA_MOBMSD02
	STA_MOBSLC01
	STA_MOBBLD01
	STA_MOBMTS01
	STA_MOBBRN01
	STA_MOBMSD01
	STA_ADLUBAUP
	STA_ADLUBADOWN
	STA_BURNPAINME
	STA_BURNPAINFOE
	STA_GROUNDSTRIKE
	STA_BOMBSHOT
	STA_CROSSDROP
	STA_METEOR
	STA_MAGICDANCEUSESPDOWN
	STA_DEEPFEARMENDOWNRATE
	STA_MENDOWNRATE
	STA_SHAMECRIUP
	STA_MOBMRS01
	STA_MOBACS01
	STA_NOTTARGET
	STA_MAGICDANCEUSESPDOWN02
	STA_MAGICDANCEUSESPDOWN03
	STA_MAGICDANCEUSESPDOWN04
	STA_MAGICDANCEUSESPDOWN05
	STA_MENDOWNRATE02
	STA_MENDOWNRATE03
	STA_MENDOWNRATE04
	STA_MENDOWNRATE05
	STA_SHAMECRIUP02
	STA_SHAMECRIUP03
	STA_SHAMECRIUP04
	STA_SHAMECRIUP05
	STA_SNSATKUP
	STA_SNSCRIUP
	STA_SNSDEFENSEUP
	STA_SNSHPUP
	STA_SNSSPUP
	STA_SNSSPEEDUP
	STA_MULTIHEAL
	STA_HIDEWC
	STA_EGLACK04
	STA_EGLACKMAD05
	STA_SALARE04
	STA_SALARE00
	STA_ADLFLOUSSIER
	STA_ADLFLOUSSIERIMT
	STA_ADLFSTUN
	STA_EGLACKMAD04
	STA_MINEICE
	STA_MINESTUN
	STA_MINEFIREVIVI
	STA_MINEICEVIVI
	STA_MINEREWARD
	STA_SETF2WCUP
	STA_SETF2ACUP
	STA_SETF4HPUP
	STA_SETF4ACDOWN
	STA_SETF4ACUP
	STA_SETF4WCUPRATE
	STA_SETF4ACUPRATE
	STA_SETA2WCUP
	STA_SETA4SPEEDUP
	STA_SETA4SPEEDDOWN
	STA_SETA4ATKSPEEDUP
	STA_SETM2MAUP
	STA_SETM2MRUP
	STA_SETM3SPUP
	STA_SETM4MAUP
	STA_SETM4MRDOWN
	STA_SETM4SPUP
	STA_SETM4MRUP
	STA_SETC2WCUP
	STA_SETC2MAUP
	STA_SETC3MRUP
	STA_SETC4MRUP
	STA_SETC4WCUP
	STA_SETC4ATKDOWN
	STA_SETC4ACUP
	STA_SETC4ACDOWN
	STA_SETC4MAUP
	STA_SETJ2WCUP
	STA_SETJ2HPUP
	STA_SETJ3SPUP
	STA_SETJ4ACDOWN
	STA_SETJ4ATKSPPEUP
	STA_SETJ4CRLUP
	STA_SETJ4WCUP
	STA_ENWCUP
	STA_ENMAUP
	STA_ENATKSPEED
	STA_ENWCRATE
	STA_ENADDDMGRATE
	STA_ENKNOCKBACKRATE
	STA_ENBINDINGRATE
	STA_ENMOVEDOWNRATE
	STA_QDAYWCUP
	STA_QDAYMAUP
	STA_QDAYEXPUP
	STA_QDAYDROPUP
	STA_SWICEWARN
	STA_SURPRISE
	STA_SWPLSWARN
	STA_SWSTNWARN
	STA_SWBRN01WARN
	STA_SWLVTWARN
	STA_AWAYBACKSPOT
	STA_RADIONBUFF
	STA_AIRIBUFF
	STA_WARLBRAINWASH
	STA_WARLBRN01
	STA_STUNCANATTACK
	STA_TRANSFORM
	STA_BALLSNOW
	STA_SNOWMAN
	STA_WARNSETBUFF
	STA_SET_VALEN_STN
	STA_SET_VALEN_Heal
	STA_VALEN_REWARD
	STA_KQEGG_SPDW
	STA_KQEGG_REWARD
	STA_KQEGG_SPUP
	STA_KQSPRING_FEAR
	STA_KQSPRING_SLOW
	STA_KQ_SPUP_BUFF
	STA_KQ_SPIM_BUFF
	STA_KQ_SPUP_RATE_BUFF
	STA_KQSPRING_ARROW
	STA_WARHBRN01
	STA_WARHBRN
	STA_STRONGER_RANGEATTACK
	STA_STRONGER_MELEEATTACK
	STA_FLAMINGBODY
	STA_COUNT30
	STA_WARHWPNBRN
	STA_ORBATKRATEUP
	STA_RECOUP
	STA_LIGHTTOUCH
	STA_TREAT
	STA_LIGHTMARK
	STA_MINHP
	STA_MOONLIGHT
	STA_LPDOTPLUS
	STA_DMGSHIELD
	STA_DELCASTTIME
	STA_SETS2WCMAUP
	STA_SETS2ACMRUP
	STA_SETS4WCMAUP
	STA_SETS4ACMRUP
	STA_SENPARTYHPUPMAIN
	STA_SENPARTYHPUP
	STA_SENPARTYHPUP1
	STA_SENEVENTEXPUP
	STA_SENEVENTDROPUP
	STA_PZL_HIDE
	STA_PZL_OCCUPY
	STA_PZL_REWARD_S
	STA_PZL_REWARD_H
	STA_PZL_REWARD_SH1
	STA_PZL_REWARD_SH2
	STA_ROUTMAGEATKUP
	STA_ARK_STN
	STA_ARK_BLD01
	STA_ARK_BLD02
	STA_ARK_BLD03
	STA_ARK_BRN01
	STA_ARK_BRN02
	STA_ARK_BRN03
	STA_ARK_THDOWN01
	STA_ARK_THDOWN02
	STA_KAHAL_STN
	STA_KAHAL_BLD
	STA_KAHAL_FEAR01
	STA_KAHAL_FEAR02
	STA_KAHAL_SHOUT
	STA_KAHAL_SPDDOWN
	STA_KAHAL_ICE
	STA_SIREN_STN1
	STA_SIREN_STN2
	STA_SIREN_NOMOVE
	STA_SIREN_KNOCKBACK1
	STA_SIREN_KNOCKBACK2
	STA_SIREN_HEAL
	STA_SIREN_LVT1
	STA_SIREN_LVT2
	STA_SIREN_BLD01
	STA_SIREN_FEAR
	STA_SIREN_BLD02
	STA_CONHPPOTION_T6
	STA_CONSPPOTION_T6
	STA_DEXPOTION_T6
	STA_ACMRPOTION_T6
	STA_STRCRIPOTION_T6
	STA_PSNRESIPOTION_T6
	STA_DSSRESIPOTION_T6
	STA_CURRESIPOTION_T6
	STA_THSCROLL_T6
	STA_TBSCROLL_T6
	STA_MRSCROLL_T6
	STA_ACSCROLL_T6
	STA_CRISCROLL_T6
	STA_MAXHPSCROLL_T6
	STA_MAXSPSCROLL_T6
	STA_MSSCROLL_T6
	STA_BERVALE_ICE01
	STA_BERVALE_ICE02
	STA_BERVALE_BLD01
	STA_BERVALE_BLD02
	STA_B_ALBI_BRN
	STA_B_ALBI_KNOCK
	STA_B_ALBI_STN
	STA_B_ALBI_FEAR
	STA_B_ALBI_DOT
	STA_B_ALBI_REFLECT
	STA_B_ALBI_ACMRUP
	STA_ADLFGCRAZY
	STA_FCITRIEDOT
	STA_LCWCMAUP
	STA_E_SLIME
	STA_E_HONEYING
	STA_E_PHINO
	STA_E_LIZARDMAN
	STA_E_KINGCRAB
	STA_E_SPARKDOG
	STA_E_LAVAVIVI
	STA_E_PHINOFLIE
	STA_E_MUSHROOM
	STA_E_SPIDER
	STA_E_B_CRACKERHUMAR
	STA_E_HELGA
	STA_EMP_STUN
	STA_EMP_KINGBLOODING
	STA_EMP_EMPBLOODING
	STA_EMP_LVT
	STA_LCACMRUP
	STA_E_FIREWORKS
	STA_ARENA_SPDUP
	STA_ARENA_STUN
	STA_ARENA_DRAGOUT
	STA_ARENA_DEFDW
	STA_ARENA_SPDDW
	STA_ARENA_ALLDW
	STA_ARENA_REWARD
	STA_ARENA_FLAG_RED
	STA_ARENA_FLAG_BLUE
	STA_ARENA_MINHP
	STA_X_ICE
	STA_X_SNOWMAN
	STA_X_REWARD01
	STA_X_REWARD02
	STA_X_REWARD03
	STA_X_REWARD04
	STA_E_SKI_ICE
	STA_E_SKI_SPEEDUP
	STA_E_SKI_REWARD
	STA_E_SKI_STUN
	STA_LAB_PURYIMPACTSTUN
	STA_C_PURYIMPACTSTUN
	STA_E_EGG2014_HOSHEMING
	STA_E_EGG2014_SELFREVIVE
	STA_E_EGG2014_EXPUP
	STA_E_EGG2014_DROPRATEUP
	STA_MOVERSTATUPSINGLE
	STA_MOVERSTATUPPARTY
	STA_MOVERSTATUP
	STA_KDSOCCER_SPEED_UP
	STA_KDSOCCER_INVINCIBLE
	STA_KQWATER_ARROW_BLUE
	STA_KQWATER_ARROW_RED
	STA_E_JACKO
	STA_E_KEBING
	STA_E_FORASCHIEF
	STA_E_H_WIN_SPEEDUP
	STA_E_H_WIN_SPEEDDOWN
	STA_ADLFLOUSSIER_H
	STA_E_USER_NEWBIE01
	STA_E_USER_NEWBIE02
	STA_E_USER_NEWBIE03
	STA_E_USER_NEWBIE04
	STA_E_USER_NEWBIE05
	STA_E_USER_COMEBACK_MAIN01
	STA_E_USER_COMEBACK_MAIN02
	STA_E_USER_COMEBACK_MAIN03
	STA_E_USER_COMEBACK_MAIN04
	STA_E_USER_COMEBACK_MAIN05
	STA_E_USER_COMEBACK01
	STA_E_USER_COMEBACK02
	STA_E_USER_COMEBACK03
	STA_E_USER_COMEBACK04
	STA_E_USER_COMEBACK05
	STA_XMAS_STATUP
	STA_IDBUFF_100
	STA_IDBUFF_80
	STA_IDBUFF_60
	STA_IDBUFF_40
	STA_IDBUFF_20
	STA_E_SNOWMANR
	STA_E_SNOWMANB
	STA_KDFARGELS_BLOOD01
	STA_KDFARGELS_BLOOD02
	STA_KDFARGELS_BLOOD03
	STA_KDFARGELS_MRDOWNRATE
	STA_KDFARGELS_AIRBORNE
	STA_KDFARGELS_ACMRDOWN
	STA_KDFARGELS_DMGNEGLECT
	STA_KDFARGELS_DOTHEAL
	STA_SDVALE01_STN
	STA_SDVALE01_WHEEL
	STA_SDVALE01_SPDUP
	STA_SDVALE01_SPDDOWN
	STA_SDVALE01_BLIND
	STA_SDVALE01_PSN
	STA_SDVALE01_ICEFIELD
	STA_SDVALE01_BRN
	STA_SDVALE01_WCMAUP
	STA_SDVALE01_KNOCK
	STA_COSMUSAACRATE
	STA_COSMUSACRI
	STA_COSMUSAALLSTAT
	STA_BH_ALBI_REFLECT
	STA_BH_ALBI_ACMRUP
	STA_E_ZOMBIE
	STA_E_MARACREW
	STA_E_MARAELITE
	STA_E_MARASAILOR
	STA_E_PSYKEN
	STA_E_PSYKENDOG
	STA_E_MEGAN
	STA_E_YETI
	STA_E_IMP
	STA_E_ROBO
	STA_E_HOB
	STA_E_PINKY
	STA_E_WARH_DEVILDOM
	STA_E_ARKNOVICE
	STA_E_ARKTECH
	STA_E_MANDRAGORA
	STA_E_S_HAYREDDIN
	STA_E_MARA
	STA_BHKARENDOT
	STA_BHKARENDIVINE
	STA_BHKARENSTATIC
	STA_BHKARENCAPTIVATE
	STA_BHKARENDOTHEAL
	STA_BHKARENSTUN
	STA_BHKARENREF
	STA_GCGCAST
	STA_SCGATK
	STA_STONEATK
	STA_COLL_BLOOD
	STA_COLL_ACID
	STA_COLL_KNOCK_01
	STA_COLL_AIRBORNE
	STA_COLL_STUN_01
	STA_COLL_STUN_02
	STA_COLL_FEAR
	STA_COLL_HEAL
	STA_COLL_STUN_03
	STA_BLA_ACMDOWN
	STA_BLA_DOT
	STA_BLA_KNOCK
	STA_BLA_FEAR
	STA_BLA_LVT
	STA_BLA_STN
	STA_BLA_ACRATE
	STA_TGGUARDIANBALL
	STA_TGHAMMER
	STA_TGROAR
	STA_TGDOT
	MAX_ABSTATEINDEX
)

//enum DispelAttr
//{
//  DA_NONE = 0x0,
//  DA_GOOD = 0x1,
//  DA_DEBUFF = 0x2,
//  DA_DISEASE = 0x3,
//  DA_POISON = 0x4,
//  DA_CURSE = 0x5,
//  DA_STUN = 0x6,
//  DA_FEAR = 0x7,
//  DA_DEEPER = 0x8,
//  DA_HIDE = 0x9,
//  DA_BOMB = 0xA,
//  DA_CHARGED = 0xB,
//  MAX_DISPELATTR = 0xC,
//};
type DispelAttr uint32

const (
	DaNone DispelAttr = iota
	DaGood
	DaDeBuff
	DaDisease
	DaPoison
	DaCurse
	DaStun
	DaFear
	DaDeeper
	DaHide
	DaBomb
	DaCharged
	MaxDispelAttr
)

//enum SubDispelAttr
//{
//  SDA_NONE = 0x0,
//  SDA_STUN = 0x1,
//  SDA_MOVESPEED = 0x2,
//  SDA_FEAR = 0x3,
//  SDA_BLOODING = 0x4,
//  SDA_DEEPER = 0x5,
//  SDA_BLIND = 0x6,
//  SDA_REVERSE = 0x7,
//  SDA_BIND = 0x8,
//  SDA_MESMERIZE = 0x9,
//  SDA_SEVERBONE = 0xA,
//  SDA_KNOCKBACK = 0xB,
//  SDA_TBMINUS = 0xC,
//  SDA_GTIRESIST = 0xD,
//  MAX_SUBDISPELATTR = 0xE,
//};
type SubDispelAttr uint32

const (
	SdaNone SubDispelAttr = iota
	SdaStun
	SdaMovespeed
	SdaFear
	SdaBlooding
	SdaDeeper
	SdaBlind
	SdaReverse
	SdaBind
	SdaMesmerize
	SdaSeverBone
	SdaKnockBack
	SdaTBMinus
	SdaGtiResist
	MaxSubDispelAttr
)

//enum AbStateSaveTypeEnum
//{
//  AST_NONE = 0x0,
//  AST_LINK_LOGOFF = 0x1,
//  AST_LINK_LOGOFF_DIE = 0x2,
//  AST_LINK_DIE = 0x3,
//  MAX_ABSTATESAVETYPEENUM = 0x4,
//};
type AbStateSaveTypeEnum uint32

const (
	AstNone AbStateSaveTypeEnum = iota
	AstLinkLogoff
	AstLinkLogoffDie
	AstLinkDie
	MaxAbStateSaveTypeEnum
)
