# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/shine-o/shine.engine.networking
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run:
          name: download module dependencies
          command: go mod download
      - run:
          name: run tests
          command: go test -v
