jobs:
  build:
    executor:
      name: go/default
      tag: '1.13'
    steps:
      - install:
          version: 1.13.6
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
orbs:
  go: circleci/go@1.1.0
version: 2.1
