# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/shine-o/shine.engine.world
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run:
          name: download module dependencies
          command: go mod download
      - run:
          name: build binary
          command: GO111MODULE=on GOOS=linux GOARCH=amd64 go build -o world
      - setup_remote_docker:
          # only available if you pay
          # docker_layer_caching: true
      - run:
          name: build docker image and push upstream
          command: |-
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t shineo/world:$TAG .
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
              docker push shineo/world:$TAG