// Code generated by "stringer -type=ShineErrorCode"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PersistenceErrDB-0]
	_ = x[PersistenceItemInvalidAmount-1]
	_ = x[PersistenceItemInvalidShnId-2]
	_ = x[PersistenceItemInvalidCharacterId-3]
	_ = x[PersistenceItemDistinctShnID-4]
	_ = x[PersistenceItemSlotUpdate-5]
	_ = x[PersistenceInventoryFull-6]
	_ = x[PersistenceCharInvalidSlot-7]
	_ = x[PersistenceCharNameTaken-8]
	_ = x[PersistenceCharNoSlot-9]
	_ = x[PersistenceCharInvalidName-10]
	_ = x[PersistenceCharInvalidClassGender-11]
	_ = x[PersistenceCharNotExists-12]
	_ = x[PersistenceUnknownInventory-13]
	_ = x[PersistenceOutOfRangeSlot-14]
	_ = x[LoginMismatchedEventType-15]
	_ = x[WorldMismatchedEventType-16]
	_ = x[WorldBadSessionType-17]
	_ = x[ZoneItemEquipFailed-18]
	_ = x[ZoneItemMissingData-19]
	_ = x[ZoneInventorySlotOccupied-20]
	_ = x[ZoneMapNotFound-21]
	_ = x[ZoneUnknownItemClass-22]
	_ = x[ZoneItemSlotChangeNoItem-23]
	_ = x[ZoneItemSlotEquipNoItem-24]
	_ = x[ZoneItemSlotIsBound-25]
	_ = x[ZoneItemSlotInUse-26]
	_ = x[ZoneItemSlotGTS-27]
	_ = x[ZoneItemUnknownInventoryType-28]
	_ = x[ZoneItemDeleteNoItem-29]
	_ = x[ZoneItemNoItemInSlot-30]
	_ = x[ZoneItemSlotIsOccupied-31]
	_ = x[ZoneItemEquipBadType-32]
	_ = x[ZoneItemSlotChangeConstraint-33]
	_ = x[ZoneMissingPlayer-34]
	_ = x[ZoneUnexpectedEventType-35]
	_ = x[ZoneMapCollisionDetected-36]
	_ = x[ZoneUnknownNpcRole-37]
	_ = x[ZoneMissingMapData-38]
	_ = x[ZoneMissingNpcData-39]
	_ = x[ZoneHandlerMaxReached-40]
	_ = x[ZoneHandlerCapacityWarning-41]
	_ = x[ZoneHandlerMaxAttemptsReached-42]
	_ = x[ZoneBadEntityType-43]
	_ = x[ZoneNilPlayerFields-44]
	_ = x[ZonePlayerSelectedUnknownEntity-45]
	_ = x[ZoneNoSessionAvailable-46]
	_ = x[UnitTestError-47]
	_ = x[PacketSnifferNotEnoughData-48]
}

const _ShineErrorCode_name = "PersistenceErrDBPersistenceItemInvalidAmountPersistenceItemInvalidShnIdPersistenceItemInvalidCharacterIdPersistenceItemDistinctShnIDPersistenceItemSlotUpdatePersistenceInventoryFullPersistenceCharInvalidSlotPersistenceCharNameTakenPersistenceCharNoSlotPersistenceCharInvalidNamePersistenceCharInvalidClassGenderPersistenceCharNotExistsPersistenceUnknownInventoryPersistenceOutOfRangeSlotLoginMismatchedEventTypeWorldMismatchedEventTypeWorldBadSessionTypeZoneItemEquipFailedZoneItemMissingDataZoneInventorySlotOccupiedZoneMapNotFoundZoneUnknownItemClassZoneItemSlotChangeNoItemZoneItemSlotEquipNoItemZoneItemSlotIsBoundZoneItemSlotInUseZoneItemSlotGTSZoneItemUnknownInventoryTypeZoneItemDeleteNoItemZoneItemNoItemInSlotZoneItemSlotIsOccupiedZoneItemEquipBadTypeZoneItemSlotChangeConstraintZoneMissingPlayerZoneUnexpectedEventTypeZoneMapCollisionDetectedZoneUnknownNpcRoleZoneMissingMapDataZoneMissingNpcDataZoneHandlerMaxReachedZoneHandlerCapacityWarningZoneHandlerMaxAttemptsReachedZoneBadEntityTypeZoneNilPlayerFieldsZonePlayerSelectedUnknownEntityZoneNoSessionAvailableUnitTestErrorPacketSnifferNotEnoughData"

var _ShineErrorCode_index = [...]uint16{0, 16, 44, 71, 104, 132, 157, 181, 207, 231, 252, 278, 311, 335, 362, 387, 411, 435, 454, 473, 492, 517, 532, 552, 576, 599, 618, 635, 650, 678, 698, 718, 740, 760, 788, 805, 828, 852, 870, 888, 906, 927, 953, 982, 999, 1018, 1049, 1071, 1084, 1110}

func (i ShineErrorCode) String() string {
	if i < 0 || i >= ShineErrorCode(len(_ShineErrorCode_index)-1) {
		return "ShineErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShineErrorCode_name[_ShineErrorCode_index[i]:_ShineErrorCode_index[i+1]]
}
