version: '3'

networks:
  intranet:
    driver: bridge

volumes:
  data:
    driver: local

services:
  #######################################
  ############## POSTGRES ###############
  #######################################
  postgresql:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      #- ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - ${DATA_PATH_HOST}/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  #######################################
  ############## REDIS ##################
  #######################################    
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
