// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package zm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MapQuery struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapQuery) Reset()         { *m = MapQuery{} }
func (m *MapQuery) String() string { return proto.CompactTextString(m) }
func (*MapQuery) ProtoMessage()    {}
func (*MapQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *MapQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapQuery.Unmarshal(m, b)
}
func (m *MapQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapQuery.Marshal(b, m, deterministic)
}
func (m *MapQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapQuery.Merge(m, src)
}
func (m *MapQuery) XXX_Size() int {
	return xxx_messageInfo_MapQuery.Size(m)
}
func (m *MapQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MapQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MapQuery proto.InternalMessageInfo

func (m *MapQuery) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ConnectionInfo struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionInfo) Reset()         { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()    {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionInfo.Merge(m, src)
}
func (m *ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionInfo.Size(m)
}
func (m *ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ConnectionInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ZoneDetails struct {
	Maps                 []int32         `protobuf:"varint,1,rep,packed,name=Maps,proto3" json:"Maps,omitempty"`
	Conn                 *ConnectionInfo `protobuf:"bytes,2,opt,name=Conn,proto3" json:"Conn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ZoneDetails) Reset()         { *m = ZoneDetails{} }
func (m *ZoneDetails) String() string { return proto.CompactTextString(m) }
func (*ZoneDetails) ProtoMessage()    {}
func (*ZoneDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *ZoneDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneDetails.Unmarshal(m, b)
}
func (m *ZoneDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneDetails.Marshal(b, m, deterministic)
}
func (m *ZoneDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneDetails.Merge(m, src)
}
func (m *ZoneDetails) XXX_Size() int {
	return xxx_messageInfo_ZoneDetails.Size(m)
}
func (m *ZoneDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneDetails proto.InternalMessageInfo

func (m *ZoneDetails) GetMaps() []int32 {
	if m != nil {
		return m.Maps
	}
	return nil
}

func (m *ZoneDetails) GetConn() *ConnectionInfo {
	if m != nil {
		return m.Conn
	}
	return nil
}

type ZoneRegistered struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ZoneID               string   `protobuf:"bytes,2,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneRegistered) Reset()         { *m = ZoneRegistered{} }
func (m *ZoneRegistered) String() string { return proto.CompactTextString(m) }
func (*ZoneRegistered) ProtoMessage()    {}
func (*ZoneRegistered) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *ZoneRegistered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneRegistered.Unmarshal(m, b)
}
func (m *ZoneRegistered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneRegistered.Marshal(b, m, deterministic)
}
func (m *ZoneRegistered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneRegistered.Merge(m, src)
}
func (m *ZoneRegistered) XXX_Size() int {
	return xxx_messageInfo_ZoneRegistered.Size(m)
}
func (m *ZoneRegistered) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneRegistered.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneRegistered proto.InternalMessageInfo

func (m *ZoneRegistered) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ZoneRegistered) GetZoneID() string {
	if m != nil {
		return m.ZoneID
	}
	return ""
}

func init() {
	proto.RegisterType((*MapQuery)(nil), "zm.MapQuery")
	proto.RegisterType((*ConnectionInfo)(nil), "zm.ConnectionInfo")
	proto.RegisterType((*ZoneDetails)(nil), "zm.ZoneDetails")
	proto.RegisterType((*ZoneRegistered)(nil), "zm.ZoneRegistered")
}

func init() {
	proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705)
}

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x9b, 0x58, 0x63, 0x3b, 0x0d, 0x11, 0xe6, 0x20, 0xa1, 0xa7, 0xb2, 0x07, 0xf1, 0x14,
	0xa4, 0xea, 0x0b, 0x68, 0x2e, 0x7b, 0x08, 0xc4, 0xf5, 0x20, 0x78, 0x8b, 0x71, 0xd4, 0x80, 0xc9,
	0xc6, 0xdd, 0xed, 0xc1, 0x3e, 0xbd, 0xcc, 0x68, 0xc0, 0x82, 0xb7, 0x19, 0xf6, 0x37, 0xff, 0x8f,
	0x85, 0xb4, 0x6f, 0x7c, 0x20, 0x57, 0x8c, 0xce, 0x06, 0x8b, 0xf1, 0xbe, 0x57, 0x6b, 0x58, 0x54,
	0xcd, 0x78, 0xbf, 0x23, 0xf7, 0x85, 0x19, 0xc4, 0xba, 0xcc, 0xa3, 0x4d, 0x74, 0x71, 0x6c, 0x62,
	0x5d, 0xaa, 0x6b, 0xc8, 0xee, 0xec, 0x30, 0x50, 0x1b, 0x3a, 0x3b, 0xe8, 0xe1, 0xd5, 0x0a, 0x51,
	0x0b, 0xb1, 0x34, 0xb1, 0xae, 0x11, 0x61, 0x5e, 0x5b, 0x17, 0xf2, 0x58, 0x6e, 0x64, 0x56, 0x1a,
	0x56, 0x4f, 0x76, 0xa0, 0x92, 0x42, 0xd3, 0x7d, 0x78, 0x46, 0xaa, 0x66, 0xf4, 0x79, 0xb4, 0x39,
	0x62, 0x84, 0x67, 0x3c, 0x87, 0x39, 0x0b, 0xcb, 0xd9, 0x6a, 0x8b, 0xc5, 0xbe, 0x2f, 0x0e, 0x8d,
	0x8c, 0xbc, 0xab, 0x5b, 0xc8, 0x58, 0xca, 0xd0, 0x5b, 0xc7, 0xb1, 0xe9, 0x05, 0x73, 0x38, 0x79,
	0xd8, 0xb5, 0x2d, 0x79, 0x2f, 0x29, 0x16, 0x66, 0x5a, 0xf1, 0x0c, 0x12, 0x66, 0x75, 0x29, 0xaa,
	0x4b, 0xf3, 0xbb, 0x6d, 0x3f, 0x21, 0xa9, 0xa4, 0x34, 0x5e, 0x02, 0x3c, 0xbe, 0x93, 0x23, 0xed,
	0xab, 0x66, 0xc4, 0x94, 0x5d, 0xa7, 0xea, 0xeb, 0x7f, 0x32, 0xa8, 0x19, 0xde, 0x40, 0x3a, 0x79,
	0xb3, 0x1a, 0x9e, 0x32, 0xf5, 0xa7, 0xdc, 0xcf, 0xd9, 0x61, 0x44, 0x35, 0x7b, 0x4e, 0xe4, 0x7b,
	0xaf, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x92, 0x13, 0x68, 0x82, 0x6e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	WhereIsMap(ctx context.Context, in *MapQuery, opts ...grpc.CallOption) (*ConnectionInfo, error)
	RegisterZone(ctx context.Context, in *ZoneDetails, opts ...grpc.CallOption) (*ZoneRegistered, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) WhereIsMap(ctx context.Context, in *MapQuery, opts ...grpc.CallOption) (*ConnectionInfo, error) {
	out := new(ConnectionInfo)
	err := c.cc.Invoke(ctx, "/zm.Master/WhereIsMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) RegisterZone(ctx context.Context, in *ZoneDetails, opts ...grpc.CallOption) (*ZoneRegistered, error) {
	out := new(ZoneRegistered)
	err := c.cc.Invoke(ctx, "/zm.Master/RegisterZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	WhereIsMap(context.Context, *MapQuery) (*ConnectionInfo, error)
	RegisterZone(context.Context, *ZoneDetails) (*ZoneRegistered, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) WhereIsMap(ctx context.Context, req *MapQuery) (*ConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhereIsMap not implemented")
}
func (*UnimplementedMasterServer) RegisterZone(ctx context.Context, req *ZoneDetails) (*ZoneRegistered, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterZone not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_WhereIsMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).WhereIsMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zm.Master/WhereIsMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).WhereIsMap(ctx, req.(*MapQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_RegisterZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RegisterZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zm.Master/RegisterZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RegisterZone(ctx, req.(*ZoneDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zm.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhereIsMap",
			Handler:    _Master_WhereIsMap_Handler,
		},
		{
			MethodName: "RegisterZone",
			Handler:    _Master_RegisterZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
