// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login-world.proto

package lw

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorldQuery struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldQuery) Reset()         { *m = WorldQuery{} }
func (m *WorldQuery) String() string { return proto.CompactTextString(m) }
func (*WorldQuery) ProtoMessage()    {}
func (*WorldQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_113e83220d40a0b5, []int{0}
}

func (m *WorldQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldQuery.Unmarshal(m, b)
}
func (m *WorldQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldQuery.Marshal(b, m, deterministic)
}
func (m *WorldQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldQuery.Merge(m, src)
}
func (m *WorldQuery) XXX_Size() int {
	return xxx_messageInfo_WorldQuery.Size(m)
}
func (m *WorldQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldQuery.DiscardUnknown(m)
}

var xxx_messageInfo_WorldQuery proto.InternalMessageInfo

func (m *WorldQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorldQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type WorldData struct {
	WorldNumber          int32    `protobuf:"varint,1,opt,name=WorldNumber,proto3" json:"WorldNumber,omitempty"`
	WorldName            string   `protobuf:"bytes,2,opt,name=WorldName,proto3" json:"WorldName,omitempty"`
	WorldStatus          int32    `protobuf:"varint,3,opt,name=WorldStatus,proto3" json:"WorldStatus,omitempty"`
	IP                   string   `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldData) Reset()         { *m = WorldData{} }
func (m *WorldData) String() string { return proto.CompactTextString(m) }
func (*WorldData) ProtoMessage()    {}
func (*WorldData) Descriptor() ([]byte, []int) {
	return fileDescriptor_113e83220d40a0b5, []int{1}
}

func (m *WorldData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldData.Unmarshal(m, b)
}
func (m *WorldData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldData.Marshal(b, m, deterministic)
}
func (m *WorldData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldData.Merge(m, src)
}
func (m *WorldData) XXX_Size() int {
	return xxx_messageInfo_WorldData.Size(m)
}
func (m *WorldData) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldData.DiscardUnknown(m)
}

var xxx_messageInfo_WorldData proto.InternalMessageInfo

func (m *WorldData) GetWorldNumber() int32 {
	if m != nil {
		return m.WorldNumber
	}
	return 0
}

func (m *WorldData) GetWorldName() string {
	if m != nil {
		return m.WorldName
	}
	return ""
}

func (m *WorldData) GetWorldStatus() int32 {
	if m != nil {
		return m.WorldStatus
	}
	return 0
}

func (m *WorldData) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *WorldData) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_113e83220d40a0b5, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserInfo struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_113e83220d40a0b5, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*WorldQuery)(nil), "lw.WorldQuery")
	proto.RegisterType((*WorldData)(nil), "lw.WorldData")
	proto.RegisterType((*User)(nil), "lw.User")
	proto.RegisterType((*UserInfo)(nil), "lw.UserInfo")
}

func init() {
	proto.RegisterFile("login-world.proto", fileDescriptor_113e83220d40a0b5)
}

var fileDescriptor_113e83220d40a0b5 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xd6, 0xa4, 0xa4, 0xd3, 0x5a, 0x70, 0x0e, 0x12, 0x82, 0x87, 0xb0, 0x17, 0x7b, 0x31,
	0x96, 0x7a, 0xf1, 0x2a, 0x14, 0x24, 0x20, 0x21, 0x46, 0xc4, 0x73, 0xda, 0xac, 0x12, 0x48, 0xb3,
	0xb2, 0xd9, 0x10, 0xfc, 0x0c, 0xff, 0x58, 0x66, 0x6c, 0x93, 0xde, 0xde, 0x7b, 0x79, 0x6f, 0x5e,
	0x66, 0x16, 0xae, 0x6a, 0xfd, 0x55, 0x35, 0x77, 0xbd, 0x36, 0x75, 0x19, 0x7f, 0x1b, 0x6d, 0x35,
	0x8a, 0xba, 0x97, 0x6b, 0x80, 0x0f, 0x92, 0x5e, 0x3b, 0x65, 0x7e, 0x10, 0xc1, 0x6d, 0x8a, 0x83,
	0x0a, 0x9c, 0xc8, 0x59, 0xcd, 0x72, 0xc6, 0xb8, 0x04, 0x51, 0x95, 0x81, 0x88, 0x9c, 0x95, 0x97,
	0x8b, 0xaa, 0x94, 0xbf, 0x0e, 0xcc, 0x38, 0xb2, 0x2d, 0x6c, 0x81, 0x11, 0xcc, 0x99, 0xa4, 0xdd,
	0x61, 0xa7, 0x0c, 0x07, 0xbd, 0xfc, 0x5c, 0xc2, 0x9b, 0xa3, 0x3d, 0xa5, 0xc1, 0x82, 0x07, 0x8f,
	0xc2, 0x90, 0x7f, 0xb3, 0x85, 0xed, 0xda, 0xe0, 0xe2, 0x2c, 0xff, 0x2f, 0x51, 0x7f, 0x92, 0x05,
	0x2e, 0x07, 0x45, 0x92, 0xd1, 0x3f, 0x66, 0xda, 0xd8, 0xc0, 0x63, 0x2b, 0x63, 0x29, 0xc1, 0x7d,
	0x6f, 0x95, 0xc1, 0x10, 0xfc, 0xae, 0x55, 0x26, 0x1d, 0x77, 0x18, 0xb8, 0x94, 0xe0, 0x93, 0x27,
	0x69, 0x3e, 0x35, 0x5e, 0xc3, 0x94, 0xf4, 0x64, 0xcb, 0x2e, 0x37, 0x3f, 0xb2, 0xcd, 0x23, 0x78,
	0x5c, 0x8d, 0xf7, 0xb0, 0x78, 0x56, 0x76, 0x5c, 0x73, 0x19, 0xd7, 0x7d, 0x3c, 0x1e, 0x2a, 0xbc,
	0x1c, 0x38, 0x7d, 0x96, 0x93, 0xcd, 0x1a, 0xbc, 0x17, 0x3a, 0x30, 0xde, 0xc2, 0xfc, 0x69, 0xbf,
	0xd7, 0x5d, 0x63, 0xb9, 0xc9, 0x27, 0x23, 0xf5, 0x86, 0x8b, 0x13, 0x22, 0x5d, 0x4e, 0x76, 0x53,
	0x7e, 0x84, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x34, 0xc5, 0x53, 0x99, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorldClient is the client API for World service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorldClient interface {
	GetWorldData(ctx context.Context, in *WorldQuery, opts ...grpc.CallOption) (*WorldData, error)
}

type worldClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldClient(cc grpc.ClientConnInterface) WorldClient {
	return &worldClient{cc}
}

func (c *worldClient) GetWorldData(ctx context.Context, in *WorldQuery, opts ...grpc.CallOption) (*WorldData, error) {
	out := new(WorldData)
	err := c.cc.Invoke(ctx, "/lw.World/GetWorldData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldServer is the server API for World service.
type WorldServer interface {
	GetWorldData(context.Context, *WorldQuery) (*WorldData, error)
}

// UnimplementedWorldServer can be embedded to have forward compatible implementations.
type UnimplementedWorldServer struct {
}

func (*UnimplementedWorldServer) GetWorldData(ctx context.Context, req *WorldQuery) (*WorldData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorldData not implemented")
}

func RegisterWorldServer(s *grpc.Server, srv WorldServer) {
	s.RegisterService(&_World_serviceDesc, srv)
}

func _World_GetWorldData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).GetWorldData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lw.World/GetWorldData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).GetWorldData(ctx, req.(*WorldQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _World_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lw.World",
	HandlerType: (*WorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorldData",
			Handler:    _World_GetWorldData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login-world.proto",
}

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	AccountInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserInfo, error)
}

type loginClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginClient(cc grpc.ClientConnInterface) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) AccountInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/lw.Login/AccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	AccountInfo(context.Context, *User) (*UserInfo, error)
}

// UnimplementedLoginServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (*UnimplementedLoginServer) AccountInfo(ctx context.Context, req *User) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfo not implemented")
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_AccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).AccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lw.Login/AccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).AccountInfo(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lw.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountInfo",
			Handler:    _Login_AccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login-world.proto",
}
